project:
  type: website
  output-dir: docs

website:
  title: "Kevin's Accounting Notes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: accounting/accounting.qmd
        text: Accounting
      - href: assurance/assurance.qmd
        text: Assurance
      - href: business/business.qmd
        text: Business
      - href: tax/tax.qmd
        text: Tax
  
  sidebar:
    - title: "Accounting"
      style: "docked"
      contents:
        - href: accounting/accounting.qmd
          text: Accounting Basics
        - href: accounting/sales.qmd
          text: Revenue and Expenses
        - href: accounting/asset.qmd
          text: Inventory and NCA
        - href: accounting/equity.qmd
          text: Equity and Capital
        - href: accounting/system.qmd
          text: Systems and Errors

    - title: "Assurance"
      style: "docked"
      contents:
        - href: assurance/assurance.qmd
          text: Assurance Basics
        - href: assurance/process.qmd
          text: Assurance Process
        - href: assurance/controls.qmd
          text: Internal Controls
        

format:
  html:
    theme: cosmo
    fontsize: 12pt
    css: styles.css
    highlight-style: arrow
    toc: true
    toc-expand: true
    grid:
      sidebar-width: 230px
      body-width: 850px
      margin-width: 270px
    number-depth: 1
    html-math-method: mathjax
    include-in-header:
      text: |
        <script src="mathjax-config.js"></script>
    include-after-body:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

editor: visual

