---
title: "Accounting Basics"
---

This page contains the basics of accounting, including the different financial statements, accounting principles, and reporting standards. The content in this section is a part of the **Accounting Fundamentals** (certificate level) for the ACA qualification.

<br />

------------------------------------------------------------------------

# **Accounting Concepts**

### Financial Statements

Summarising transactions: this provides information about the company to stakeholders. Stakeholders can include shareholders, investors, employees, banks, or any users that may interact with the company. This takes the form of 4 financial statements:

+-------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| **Statement of Financial Position** | Reflects the **position** of a business at a **specific point in time**.                                                                         |
|                                     |                                                                                                                                                  |
| (Balance Sheet)                     | This includes the assets (the things the company owns), the liabilities (what the company owes), and the equity (the investment in the company). |
+-------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| **Statement of Profit or Loss**     | Reflects the **performance** (profitability) of a business **over a period** of time (usually a year).                                           |
|                                     |                                                                                                                                                  |
| (Income State)                      | It starts with the revenue of the year, then subtracts different revenue expenditures until we reach the net profit figure.                      |
+-------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| **Statement of Changes in Equity**  | Shows how **equity** (stock/shares/retained earnings) are changing in a business over a **period of time**.                                      |
|                                     |                                                                                                                                                  |
|                                     | Only for incorporated companies.                                                                                                                 |
+-------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| **Statement of Cash Flows**         | Shows how **cash** is entering and exiting the business over a period of time.                                                                   |
+-------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[30,70\]"}

<br />

### Types of Businesses

There are several types of businesses, that will affect the reporting standards and legal liability of businesses.

+-----------------+------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+
| **Sole Trader** | A business owned and operated by one person.                                                         | **Personally liable** for any losses.                                                   | Only need to file accounts for tax purposes.                                                          | Owner has capital in the business. No corporation tax, only pay income tax on profits.                                               |
+-----------------+------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+
| **Partnership** | A business owned and operated by a joint number of partners (a collection of sole traders).          | **Personally liable** for any losses.                                                   | Only need to file accounts for tax purposes.                                                          | Owners have capital in the business, split profits based on agreed profit ratio. No corporation tax, only pay income tax on profits. |
+-----------------+------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+
| **Company**     | Separate legal entity. It is owned by **shareholders**, who elect **directors** to run the business. | ***Limited liability*** - the shareholders/owners are not personally liable for losses. | Required to provide more details in their financial statements - must be provided to Companies House. | Owners/shareholders have equity in the business. Pay corporation tax.                                                                |
|                 |                                                                                                      |                                                                                         |                                                                                                       |                                                                                                                                      |
|                 | -   Limited Liability Companies (LLC): privately owned, no trading shares.                           |                                                                                         |                                                                                                       |                                                                                                                                      |
|                 | -   Public Limited Company (PLC): publicly owned, shares are traded.                                 |                                                                                         |                                                                                                       |                                                                                                                                      |
|                 | -   Limited Liability Partnerships (LLP): a partnership that is a separate legal entity.             |                                                                                         |                                                                                                       |                                                                                                                                      |
+-----------------+------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[15,30,15,20,20\]"}

::: {.callout-note collapse="true" appearance="simple"}
## Personal Liability

When saying personal liability, this means people can have their personal belongings repossessed to pay off the debts of a business.

-   A person's private car and house can be taken away.

In limited liability, only the money the person invested can be lost. Their personal belongings are not at risk even if the company is in debt.
:::

::: {.callout-note collapse="true" appearance="simple"}
## Business Entity Concept

No matter the type of business, their financial statements should only include transactions related to the business. This is the business entity concept - the business is a separate entity (even if legal liability is not separate).

-   Ex. most sole traders should have a separate account for personal and business matters. Personal matters should not be included in the financial statements.
-   If a sole trader needs to pull things in and out of a business, they invest capital into the business (equity increase), or draw from the business (equity decrease).
:::

<br />

### Principles and Conventions

There are a set of principles that characterise good financial information and reporting, and a set of conventions for accounting standards:

::: panel-tabset
## Accounting Principles

These are the principles that make up good financial statements.

+--------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Relevance**                              | Information should be useful, and has the ability to influence decisions of users. It helps users confirm past predictions, and helps users assess the future of the business. Non-material things are not very important.                     |
+--------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Faithful Representation / Reliabiility** | Information in the statements should represent reality correctly and accurately. Information should be neutral, free from bias, and free from errors. No speculation, just what is there.                                                      |
+--------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Comparability**                          | Information should be reported in a similar manner (with same methods) for different firms over the same time period to allow for comparisons between firms. They should also be reported similarly between years to allow for trend analysis. |
+--------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Verifiability**                          | The information should be able to be verified to be accurate (generally through an audit), and has evidence to back up the assertions.                                                                                                         |
+--------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Timeliness**                             | Information should be available quickly to influence decisions - info should not be delayed so that it is out-of-date.                                                                                                                         |
+--------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Understandability**                      | Information should be expressed clearly and according to standards so it is understood.                                                                                                                                                        |
+--------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[30,70\]"}

## Accounting Conventions

Accounting is a set of standards to record business transactions, allowing comparisons between companies, and for stakeholders to make decisions. It is important the financial information follows certain conventions:

+---------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Convention                | Description                                                                                                                                                                            | Example                                                                                                                                                                                                |
+===========================+========================================================================================================================================================================================+========================================================================================================================================================================================================+
| **Historic Cost**         | We should report things at historic cost: the cost at acquisition. Current valuations are subjective and can change.                                                                   | If a firm bought a property for £50m, it should be listed as £50m.                                                                                                                                     |
+---------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Prudence/Conservatism** | We should be conservative in making judgmenets. Under-promise (don't overstate profits/good things, always state even potential bad things like losses and liabilities).               | If a firm has a reasonable chance of incurring a liability, we should notify investors of this ahead of time. However, we should not notify investors of good news (profits) before they are realised. |
+---------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Money Measurement**     | In general, financial statements should include things that can be valued in monetary terms. This is to avoid subjectiveness.                                                          | Things like favourable geographic location cannot be given a monetary value, so are at risk of being inflated by management.                                                                           |
+---------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Matching**              | Expenses should be matched to the revenues they generate.                                                                                                                              | If we sell a car this period, but haven't yet received the payment, we should still match the expense of the car to this sale this period.                                                             |
+---------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Going Concern**         | We report statements, with the assumption that the business will continue operations for the foreseeable future. If this isn't the case, we should recommend to not use going concern. | If Microsoft is suing a small firm that will cease operations if they lose, and the firm has a 95% chance of losing, it is reasonable to notify investors about this.                                  |
+---------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[20,45,35\]"}
:::

<br />

### Accounting Equation

> **Assets = Liabilities + Equity** $\implies$ **Assets - Liabilities = Equity**

::: panel-tabset
## Assets

Assets are things the company owns, that helps it generate profit. They are divided into current assets and non-current assets.

+------------------------+------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+
| **Current Assets**     | Assets you plan to liquidate (turn into cash, move around, sell) within the next 12 months as part of making business. | Inventory, Cash, Cash at bank, Trade Receivables (things customers need to pay to you), Prepayments. |
+------------------------+------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+
| **Non-Current Assets** | Assets you do not plan to sell/move on from in the next 12 months, but still help generate profit.                     | Property Plant Equipment (PPE), Fixtures, Vehicles, Factories, Computers, Capital Expenditures.      |
+------------------------+------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[25,40,35\]"}

## Liabilities

Liabilities are things the company owes to external lenders. For example, money they owe to the bank or suppliers. They are divided into current and non-current liabilities.

+-----------------------------+-------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+
| **Current Liabilities**     | Things you owe to external lenders that are due within 12 months.       | Short Term Borrowings, Trade Payables (things you need to pay), Provisions, Overdrafts. |
+-----------------------------+-------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+
| **Non-Current Liabilities** | Things you owe to external lenders that are due in more than 12 months. | Bank Loan, Bonds/Debuntures/Loan Notes.                                                 |
+-----------------------------+-------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[25,40,35\]"}

## Equity/Capital

Equity (Capital for non-incorporated sole-traders/partnerships) is the investment of the shareholders of the company. Equity consists of the following accounts:

+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+
| **Shares/Capital**    | The direct investment of shareholders/owners. This includes share premium and share capital (discussed later).                             | Share Premium, Share Capital, Injections |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+
| **Retained Earnings** | The accumulated profits/loss of the business. Each new year profit is added/subtracted from it.                                            | Retained Earnings.                       |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+
| **Drawings**          | When the owners take out money. This can be a sole trader taking a computer out to give to their kid, or dividends issued to shareholders. | Dividends, Drawings.                     |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+

: {.bordered .sm tbl-colwidths="\[25,40,35\]"}
:::

The accounting equation is **always true**: the statement of financial position's listed assets, liabilities, and equity should always equal/balance.

This equation implies the **duality concept**: that every transaction that affects one side of the equation, must also affect the other side of the equation, in order to keep the accounting equation true.

::: {.callout-note collapse="true" appearance="simple"}
## Net Assets

Net assets are defined as:

> **Net Assets = Assets - Liabilities**

Net current assets are defined as:

> **Net Current Assets = Current Assets - Current Liabilities**
:::

<br />

### CapEx and Expenses

There are two main types of expenditures accounts that are also important to note, since these go on different financial statements:

+-------------------------+----------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------+
| Type of Expenditure     | Description                                                                                                                            |                                                                                                                                                |
+=========================+========================================================================================================================================+================================================================================================================================================+
| **Capital Expenditure** | Expenditure used to obtain/improve long-term assets, the **improve or enhance the earning capacity** of the company.                   | -   Buying a new factory, vehicle for delivery, property, land, and others.                                                                    |
|                         |                                                                                                                                        | -   Expanding a factory to enhance future economic income.                                                                                     |
|                         | Not expenditure for repairs/maintenance that only keeps/restores long-term assets at their existing capacity.                          | -   Any other expenses (delivery costs, legal fees) needed to begin using any new factory, vehicle, etc.                                       |
|                         |                                                                                                                                        |                                                                                                                                                |
|                         | Go into **non-current assets** on the balance sheet.                                                                                   |                                                                                                                                                |
+-------------------------+----------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------+
| **Revenue Expenditure** | Expenditures incurred for operating the company. This includes purchases of raw material, inventory, operating expenses, tax expenses. | -   Cost of sales: inventory costs for what they have sold.                                                                                    |
|                         |                                                                                                                                        | -   Operating expenses like salaries, rent, utilities, interest payments, tax expenses.                                                        |
|                         | Also includes repairs/maintenance to ensure existing assets work properly (without improving the capacity of these assets).            | -   Routine expenses to maintain and operate long-term assets, such as repairs, repainting, gasoline for vehicles, insurance costs for assets. |
|                         |                                                                                                                                        |                                                                                                                                                |
|                         | Go into **income statement** as expenses.                                                                                              |                                                                                                                                                |
+-------------------------+----------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[20,40,40\]"}

::: {.callout-note collapse="true" appearance="simple"}
## Individual Judgement

Many figures in financial statements are derived from the application of judgment in applying accounting concepts. This means different people can reach different conclusions.

-   Example: determining whether expenditure is revenue or capital.
-   Other examples: valuation of buildings, depreciation, etc.

Refer to the International Ethics Standards Borad for Accountants (IESBA) and the ICAEW code of ethics, and their [ethical principles](../assurance/assurance.qmd#ethical-principles).
:::

<br />

### Debits and Credits

We know from the accounting equation, there is a **duality concept**. Another way to specify this concept is with **debits** (Dr) and **credits** (Cr). They are just fancy ways to say positive and negative amounts. Importantly, debits and credits do different things for different accounts.

+---------------------------------------------------------------+-----------+-----------+
| Account                                                       | Debit     | Credit    |
+===============================================================+:=========:+:=========:+
| **Assets** (all)                                              | **+**     | **-**     |
+---------------------------------------------------------------+-----------+-----------+
| **Liabilities** (all)                                         | **-**     | **+**     |
+---------------------------------------------------------------+-----------+-----------+
| **General Equity** (Share capital, share premium, injections) | **-**     | **+**     |
+---------------------------------------------------------------+-----------+-----------+
| **Expenses** (negative equity)                                | **+**     | **-**     |
+---------------------------------------------------------------+-----------+-----------+
| **Drawings/Dividends** (negative equity)                      | **+**     | **-**     |
+---------------------------------------------------------------+-----------+-----------+

: {.bordered .sm tbl-colwidths="\[50,25,25\]"}

The debits and credits of each recorded transaction should balance. See the preparing financial statements to see how we turn debit and credit records into financial statements.

<br />

<br />

------------------------------------------------------------------------

# **Bookkeeping Basics**

### Recording Transactions

For example, imagine I invest £5,000 into the firm's bank account. In double entry accounting, we know the debits and credits are:

-   Dr. Cash (Asset) £5,000
-   Cr. Equity (Equity) £5,000

Every transaction's debits and credits should be equal. You can have more than one debit or credit, but the total debits and credits must equal.

Then, list the debits and credits in the correct accounts. Each transaction's debits and credits should balance. However, each t-account individually does not need to be balanced.

+:-------------------------------------------:+:-------------------------------------------:+
| **Equity**                                  | **Cash (Asset)**                            |
|                                             |                                             |
| | Debits | Credits |                        | | Debits | Credits |                        |
| |:------:|:-------:|                        | |:------:|:-------:|                        |
| |   £0   | £5,000  |                        | | £5,000 |   £0    |                        |
|                                             |                                             |
| : {.bordered .sm tbl-colwidths="\[50,50\]"} | : {.bordered .sm tbl-colwidths="\[50,50\]"} |
+---------------------------------------------+---------------------------------------------+

Note: for [income statement accounts (revenue, purchases, expenses), the starting balance of all accounts at the beggining of the period should be reset to 0]{.mark}. For [all other accounts (on the balance sheet), the starting balance of debits/credits should be carried over]{.mark} from the previous period.

For more details on specific types of transactions, see the left sidebar for details.

<br />

### Closing the Accounts

At the end of the year, we need to **close the accounts** (except inventory and cost of sales, see above). The steps are as follows:

1.  Sum up each side of debits and credits. Find the side (debit or credit) with the higher sum value. Put this at the bottom of both sides:

+-----------------------+-----------------------+
| Debits                | Credits               |
+:=====================:+:=====================:+
| £1000                 | £600                  |
+-----------------------+-----------------------+
| **highest: £1000**    | **highest: £1000**    |
+-----------------------+-----------------------+

: {.bordered .sm tbl-colwidths="\[50,50\]"}

2.  Look at the side with the lower value. [Find the "difference" between the lower and higher values, and put it on the side of the lower side]{.mark}. This difference is called the **balance carried forward (c/f)**. Write it on the smaller side.

+--------------------+-----------------------+
| Debits             | Credits               |
+:==================:+:=====================:+
| £1000              | £600                  |
+--------------------+-----------------------+
| \-                 | **balance c/f £400**  |
|                    |                       |
| **highest: £1000** | **highest: £1000**    |
+--------------------+-----------------------+

: {.bordered .sm tbl-colwidths="\[50,50\]"}

3.  On the side with the larger value, copy the balance c/f value to that side on the very bottom, called the **balance brought forward (b/f)**.

+------------------------------------+--------------------+
| Debits                             | Credits            |
+:==================================:+:==================:+
| £1000                              | £600               |
+------------------------------------+--------------------+
| \-                                 | **c/f £400**       |
|                                    |                    |
| **highest: £1000**                 | **highest: £1000** |
|                                    |                    |
| [**balance b/f £400**]{.underline} |                    |
+------------------------------------+--------------------+

: {.bordered .sm tbl-colwidths="\[50,50\]"}

4.  The [balance b/f is the final balance of the account]{.mark}. This final balance (note if it is a debit or credit) will go into the trial balance.
    -   For income statement accounts (revenue, purchases, expenses), the starting balance will be [reset to 0]{.mark} for the next year.
    -   For balance sheet accounts (all not on the income statement), the balance b/f will be [starting balance]{.mark} for next year's accounts.

<br />

### Trial Balance

A trial balance is simply a list of all accounts, and their closing balances. It takes the form of the following:

+-------------------------+--------------------------+--------------------------+
|                         | Dr £                     | Cr £                     |
+=========================+==========================+==========================+
| Cash                    | 3,000                    |                          |
+-------------------------+--------------------------+--------------------------+
| Revenue                 |                          | 4,000                    |
+-------------------------+--------------------------+--------------------------+
| Rent Expense            | 3,000                    |                          |
+-------------------------+--------------------------+--------------------------+
| Capital                 |                          | 2,000                    |
+-------------------------+--------------------------+--------------------------+
| [**TOTAL**]{.underline} | [**£6,000**]{.underline} | [**£6,000**]{.underline} |
+-------------------------+--------------------------+--------------------------+

: {.bordered .sm tbl-colwidths="\[50,25,25\]"}

The trial balance should **balance**: [the total number of debits and credits should be equal]{.mark}.

-   Make sure you put the value of the account into the correct column (debit or credit).
-   A quick way to check if the column is correct, is that revenue should always be in the debit column (you cannot have negative revenue, and debit increases revenue), and expenses/drawings should always be in the credit column.

This trial balance will help us create both the income statement, and the balance sheet.

**NOTE: before you continue on to compiling statements, you will need to check if there are adjustments to be made**. Adjustments are to correct for accrual accounting procedures, and include accrued payments/prepayments.

<br />

### Income Statement

To create the income statement from the trial balance, we just simply put the closing balances of the relevant accounts into the following form. More details on income and expense accounting are on the income accounting page.

+-------------------------------------------------------------------------+----------+----------+
|                                                                         | Dr £     | Cr £     |
+=========================================================================+==========+==========+
| Revenue                                                                 |          | £–       |
+-------------------------------------------------------------------------+----------+----------+
| Cost of Sales (inventory costs for sold goods, inward delivery)         | £–       |          |
|                                                                         |          |          |
| **Gross Profit**                                                        |          |          |
+-------------------------------------------------------------------------+----------+----------+
| Distribution Expenses (delivery outward to customers, vehicle expenses) | £–       |          |
|                                                                         |          |          |
| Administrative Expenses (salary, rent, utilities)                       | £–       |          |
|                                                                         |          |          |
| **Operating Profit**                                                    |          |          |
+-------------------------------------------------------------------------+----------+----------+
| Finance Expense (interest)                                              | £–       |          |
|                                                                         |          |          |
| **Profit Before Tax**                                                   |          |          |
+-------------------------------------------------------------------------+----------+----------+
| Tax Expense                                                             | £–       |          |
|                                                                         |          |          |
| **Net Profit**                                                          |          |          |
+-------------------------------------------------------------------------+----------+----------+

: {.bordered .sm tbl-colwidths="\[50,25,25\]"}

The **bolded** parts are not accounts, and should be left blank until all accounts are filled in. Then, to calculate the bolded metrics, sum up all the credits, and all the debits, [above]{.underline} the bolded metric (all the way to the top). Then do the sum of credits minus the sum of debits.

<br />

### Balance Sheet

To compile the balance sheet, simply list the remaining non-income statement accounts into their proper location. Remember that for assets, debit is positive and credit is negative. For liabilities and equity, debit is negative and credit is positive. More details on assets are provided on the asset accounting page.

+------------------------------------+----------------+
| Non-Current Assets                 | \-             |
|                                    |                |
| -   Accounts go here               | -   £–         |
|                                    |                |
| Current Assets                     | \-             |
|                                    |                |
| -   Accounts go here               | -   £–         |
|                                    |                |
| **Total Assets**                   | £–             |
+------------------------------------+----------------+
| Equity                             | \-             |
|                                    |                |
| -   Accounts go here               | -   £–         |
|                                    |                |
| Non-Current Liabilities            | \-             |
|                                    |                |
| -   Accounts go here               | -   £–         |
|                                    |                |
| Current Liabities                  | \-             |
|                                    |                |
| -   Accounts go here               | -   £–         |
|                                    |                |
| **Total Equity + Assets**          | £–             |
+------------------------------------+----------------+

: {.bordered .sm tbl-colwidths="\[50,50\]"}

<br />

### Cash Flow Statement

Since the income statement (and net profit/loss) is recorded with accrual accounting, it does not record when cash is received/leaving a business. However, cash is still important as cash is needed to pay suppliers and liabilities.

The cash flow statement records how cash flows in and out of a business. It is divided into 3 parts:

1.  **Cash flow from operating activities**: this includes cash flows from core business operations, such as from sales, COGS, and operating expenses.
2.  **Cash flow from investing activities**: this includes cash flow from the purchase and disposal of assets.
3.  **Cash flow from financing activities**: this includes cash flows from liabilities/equity (loans, shares) and dividends.

There are two ways to prepare a cash flow statement.

-   **Direct method**: this is basically recording and counting all the inflows and outflows of cash.
-   **Indirect method** (more common): it uses different details from the income statement and balance sheet to work out the cash flow. Essentially, it is undoing the accruals/prepayments and payables/receivables to calculate cash flow.

<br />

**Cash flow from operating activities**:

1.  Start with the [profit before tax]{.underline} figure from the income statement.
2.  *Add* [finance costs]{.underline} (so if you spend £X on finance costs, do + £X).
3.  *Subtract* [finance income]{.underline} (so if you earn £X in finance income, do -£X).
4.  *Subtract* [profits from disposal of non-current assets]{.underline} (so if you earn £X, do -£X, and if you lost £X, do +£X).
5.  *Add* [depreciation expense]{.underline} (so if you spent £X on depreciation costs, do +£X).
6.  *Add* [amoritsation expense]{.underline} (so if you spent £X on amoritsation, do +£X).
7.  *Subtract* [change in inventory]{.underline} (so if inventory increased from last period, subtract. If inventory decreased from last period, add).
8.  *Subtract* [change in trade receivables]{.underline} (so if receivables increased from last period, subtract. If receivables decreased from last period, add).
9.  *Add* [change in trade payables]{.underline} (so if payables account increased from last period, add. If payables account decreased, subtract).
10. *Add* [change in accruals]{.underline} (so if accruals account increased from last period, add. If accruals account decreased, subtract).
11. *Subtract* [tax expense]{.underline} (so if you spent £X on tax, do -£X).
12. *Subtract* [interest paid]{.underline} (so if you spent £X on tax, do -£X).

**Cash flow from investing activities**

1.  *Subtract* [amount spent on property, plant, and equipment]{.underline} (so if you spent £X, do -£X).
2.  *Subtract* [amount spent on intangible assets]{.underline} (so if you spent £X, do -£X).
3.  *Add* [proceeds from sale of property, plant, and equipment]{.underline} (so if you gained £X, do +£X).

**Cash flow from financing activities**

1.  *Add* [proceeds from issue of shares]{.underline} (so if you gained £X, do +£X).
2.  *Add* [change in borrowings]{.underline}.
3.  *Subtract* [dividends paid]{.underline} (so if you paid £X, do -£X).