---
title: "Cash Flow Statement"
---

### Overview

Since the income statement (and net profit/loss) is recorded with accrual accounting, it does not record when cash is received/leaving a business. However, cash is still important as cash is needed to pay suppliers and liabilities.

The cash flow statement records how cash flows in and out of a business. It is divided into 3 parts:

1.  **Cash flow from operating activities**: this includes cash flows from core business operations, such as from sales, COGS, and operating expenses.
2.  **Cash flow from investing activities**: this includes cash flow from the purchase and disposal of assets.
3.  **Cash flow from financing activities**: this includes cash flows from liabilities/equity (loans, shares) and dividends.

There are two ways to prepare a cash flow statement.

-   **Direct method**: this is basically recording and counting all the inflows and outflows of cash.
-   **Indirect method** (more common): it uses different details from the income statement and balance sheet to work out the cash flow. Essentially, it is undoing the accruals/prepayments and payables/receivables to calculate cash flow.

<br />

### Indirect Method

**Cash flow from operating activities**:

1.  Start with the [profit before tax]{.underline} figure from the income statement.
2.  *Add* [finance costs]{.underline} (so if you spend £X on finance costs, do + £X).
3.  *Subtract* [finance income]{.underline} (so if you earn £X in finance income, do -£X).
4.  *Subtract* [profits from disposal of non-current assets]{.underline} (so if you earn £X, do -£X, and if you lost £X, do +£X).
5.  *Add* [depreciation expense]{.underline} (so if you spent £X on depreciation costs, do +£X).
6.   *Add* [amoritsation expense]{.underline} (so if you spent £X on amoritsation, do +£X).
7.  *Subtract* [change in inventory]{.underline} (so if inventory increased from last period, subtract. If inventory decreased from last period, add).
8.  *Subtract* [change in trade receivables]{.underline} (so if receivables increased from last period, subtract. If receivables decreased from last period, add).
9.  *Add* [change in trade payables]{.underline} (so if payables account increased from last period, add. If payables account decreased, subtract).
10. *Add* [change in accruals]{.underline} (so if accruals account increased from last period, add. If accruals account decreased, subtract).
11. *Subtract* [tax expense]{.underline} (so if you spent £X on tax, do -£X).
12. *Subtract* [interest paid]{.underline} (so if you spent £X on tax, do -£X).

**Cash flow from investing activities**

1.  *Subtract* [amount spent on property, plant, and equipment]{.underline} (so if you spent £X, do -£X).
2.  *Subtract* [amount spent on intangible assets]{.underline} (so if you spent £X, do -£X).
3.  *Add* [proceeds from sale of property, plant, and equipment]{.underline} (so if you gained £X, do +£X).

**Cash flow from financing activities**

1.  *Add* [proceeds from issue of shares]{.underline} (so if you gained £X, do +£X).
2.  *Add* [change in borrowings]{.underline}.
3.  *Subtract* [dividends paid]{.underline} (so if you paid £X, do -£X).