---
title: "Equity and Capital"
---

This page covers information on capital (for sole traders and partnerships) and equity (for companies). The content in this section is a part of the **Accounting Fundamentals** (certificate level) for the ACA qualification.

<br />

------------------------------------------------------------------------

# **Capital**

### Sole Traders

For sole traders, equity is considered capital. The capital part of the balance sheet contains:

+-----------------------+--------------------------------------------------------------------------------+
| **Injections**        | This is the money the sole trader has put into the business.                   |
+-----------------------+--------------------------------------------------------------------------------+
| **Drawings**          | This is the money (or assets) the sole trader has withdrawn from the business. |
+-----------------------+--------------------------------------------------------------------------------+
| **Retained Earnings** | This is the accumulated profits/losses of the business.                        |
+-----------------------+--------------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[30,70\]"}

As noted above, drawings can be either cash or assets. For example, a sole trader could draw out a bike for their child. Drawings are recorded as:

-   **Dr Drawings** (negative equity).
-   **Cr Cash/Assets**

<br />

### Partnerships

Partnerships are a business with multiple owners (like multiple sole traders).

As a result, each is entitled to a share of the profits (and losses). They thus all have their own capital section.

-   The partnership agreement determines how these profits will be shared. Generally, the sharing of profits is defined by the **profit share ratio**. If there is no partnership agreement, profit share is always equal.

Each partner has two accounts in the capital section:

+---------------------+---------------------------------------------------------------------------------+
| **Capital Account** | Contains the injections of the specific partner.                                |
+---------------------+---------------------------------------------------------------------------------+
| **Current Account** | Contains the profit share of the partner, and the drawings they have taken out. |
+---------------------+---------------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[30,70\]"}

Thus, the capital section of partnership financial statements looks like this:

+----------------------+----------------+----------------+
| **Capital Accounts** | Partner A      | £X             |
|                      |                |                |
|                      | Partner B      | £X             |
+----------------------+----------------+----------------+
| **Current Accounts** | Partner A      | £X             |
|                      |                |                |
|                      | Partner B      | £X             |
+----------------------+----------------+----------------+

: {.bordered .sm tbl-colwidths="\[40,30,30\]"}

<br />

------------------------------------------------------------------------

# **Company Equity**

### Equity Accounts

Companies are owned by shareholders, who hold **equity** in the business. Equity is divided into the following parts:

+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Ordinary Share Capital**   | Also called share capital or ordinary share. Involved in the issuing of shares, see below for details.                                                                                          |
+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Preference Share Capital** | Involved in the issuing of shares, see below for details.                                                                                                                                       |
+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Share Premium**            | Involved in the issuing of shares, see below for details.                                                                                                                                       |
+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Retained Earnings**        | This is the accumulated profits/losses from the company (each new year profit/loss is added to this account). Dividends are withdrawn and paid out from retained earnings, see dividends below. |
+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Other Reserves**           | An additional account that can store resources for certain things.                                                                                                                              |
+------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[30,70\]"}

<br />

### Issuing Shares

When you set up a business, you set a **par (or nominal) value**: the "default" value for each share. Most commonly £1 or £0.5.

When you issue new shares, you can choose to value each share at any value above the par value. This price is called the **issue price**.

-   This is NOT the market value, and the market value is not involved in financial statements.

The difference between the issue price and the par value is the **excess value**.

$$
\text{excess value} = \text{issue price} - \text{par value}
$$

When we issue new shares, and they are bought, the proceeds are recorded as follows:

+---------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| **Dr Cash** Issue Price $\times$ \# of Shares                 | The issue price is what you get when someone buys the share. So we record all proceeds to cash. |
+---------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| **Cr Ordinary Share Capital** Par Value $\times$ \# of Shares | We credit the par value of the issued shares to ordinary share capital.                         |
+---------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| **Cr Share Premimum** Excess Value $\times$ \# of Shares      | We credit the excess value of the issued shares to share premium.                               |
+---------------------------------------------------------------+-------------------------------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[50,50\]"}

Every share (ordinary share) contains rights to vote, and may or may not receive dividends.

**Rights Issue** is when you offer new shares to existing shareholders. The value of these shares (the issue price) is typically lower than market values, but always above the par value.

-   The recording of issuing rights issues are the same as issuing standard shares.

<br />

### Bonus Issue

**Bonus Issues** of shares is when you gift shares to existing shareholders. This may be because you want to keep shareholders happy.

Bonus Issues are often issued at a ratio. For example, a bonus issue of 1:4 means for every 4 shares you own, you will get 1 new bonus share.

Bonus issues are always valued at the par value. The recording of the transaction is:

+---------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
| **Cr Ordinary Share Capital** Par Value $\times$ \# of Shares | The issue price is what you get when someone buys the share. So we record all proceeds to cash.                                                    |
+---------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
| **Dr Share Premium\*** Par Value $\times$ \# of Shares        | \*If there is not enough value in the share premium account, we can Dr from other equity reserves, including retained earnings and other reserves. |
|                                                               |                                                                                                                                                    |
|                                                               | However, you only want to Dr from retained earnings if you have no other option, as dividends are issued from retained earnings.                   |
+---------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[35,55\]"}

**Bonus Shares do not generate cash**. We are simply reassigning values within our accounts.

-   In other words, Bonus shares are essentially "diluting" existing shares so you can give some extra to existing share holders.

<br />

### Dividends

Dividends are paid to shareholders by taking out money from retained earnings.

+--------------------------------------+-----------------------------------------------------------------------------------+
| **Dr Retained Earnings**             | Take value out of retained earnings (the accumulated profit/loss of the company). |
+--------------------------------------+-----------------------------------------------------------------------------------+
| **Cr Dividends Payable (Liability)** | A liability that needs to be paid. When paid, Cr Cash and Dr the liability.       |
+--------------------------------------+-----------------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[35,55\]"}

Note: Dividends are **not expense**. They do not go on the income statement.

Note: Redeemable preference shares have "dividends", but they are actually considered interest payments/finance costs.

<br />

### Preference Shares

Preference shares **do not carry voting rights**. However, to make up this, they have **priority over receiving dividends**.

Furthermore, dividends are typically calculated as a percentage of the nominal value of the share. Ex. 5 percent annual dividend.

-   The nominal value of a preference share does not have to be the same as the par/nominal value of ordinary shares.

Importantly, there are two types of preference shares, that are accounted differently.

+------------------------------------+------------------------------------------------------------------------------------------------------------------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------+
| **Irredeemable Preference Shares** | The company cannot buy back the shares.                                                                          | They are classed as **equity**.      | The dividend is drawn from the retained earnings. Thus, does not go on income statement.                                   |
+------------------------------------+------------------------------------------------------------------------------------------------------------------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------+
| **Redeemable Preference Shares**   | Company can buy back the shares (and typically does after a set period). Similar to bonds/debentures/loan notes. | They are classed as **liabilities**. | Since it is a liability, the dividend is considered **interest payments/finance cost**. This goes on the income statement. |
+------------------------------------+------------------------------------------------------------------------------------------------------------------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[20,30,20,30\]"}

When issuing preference shares, the double entry is as follows:

+------------------------------------+---------------------------------------------------------------------------+
| **Irredeemable Preference Shares** | Cr Preference Share Capital (Equity): Nominal Value $\times$ \# of Shares |
|                                    |                                                                           |
|                                    | Dr Cash: Nominal Value $\times$ \# of Shares                              |
+------------------------------------+---------------------------------------------------------------------------+
| **Redeemable Preference Shares**   | Cr Preference Shares (Liability): Nominal Value $\times$ \# of Shares     |
|                                    |                                                                           |
|                                    | Dr Cash: Nominal Value $\times$ \# of Shares                              |
+------------------------------------+---------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[30,70\]"}

<br />

### Bonds/Debentures

Bonds/Debentures/Loan Notes are a way for companies to raise money. Essentially, they are loans from the market, rather than from banks.

For example, company bond might be £100. When a investor buys the bond, they are lending £100 to the company. This £100 will be paid in a set time.

+------------------+---------------------------------------------------------------------------------+
| **Dr Cash**      | The firm gains the money the investor paid for the bond.                        |
+------------------+---------------------------------------------------------------------------------+
| **Cr Loan Note** | Called loan note or bonds or debentures. These are **non-current liabilities**. |
+------------------+---------------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[30,70\]"}

The investor is entitled to interest for the duration of the bond, specified as a percentage of the value paid from the bond. This percentage is called the **coupon rate**.

Each year, the interest is paid as follows:

+--------------------------------------+----------------------------------------+
| **Cr Cash**                          | Decrease cash to pay for the interest. |
+--------------------------------------+----------------------------------------+
| **Dr Interest Expense/Finance Cost** | This goes on the income statement.     |
+--------------------------------------+----------------------------------------+

: {.bordered .sm tbl-colwidths="\[30,70\]"}

Note: while bonds/debentures are not equity, they can generally only be issued by incorporated companies.

<br />

### Statement of Equity

Explains how the value of equity has changed during the year for a company.

-   It lists the opening balance of each equity account.
-   Then it shows changes to this equity over the time period (usually a year).
-   The closing balance of the statement of changes in equity will equal the total equity in the end-of-period balance sheet.

|   | Share Capital | Share Premium | Retained Earnings | Total |
|----|:--:|:--:|:--:|:--:|
| Balance at Opening | £X | £X | £X | [£X]{.underline} |
| Profit/(Loss) for Year |  |  | £X/(£X) |  |
| Issue of Shares | £X | £X |  |  |
| Dividends Paid |  |  | (£X) |  |
| **Total** | **£X** | **£X** | **£X** | [**£X**]{.underline} |

: {.bordered .sm tbl-colwidths="\[20,20,20,20,20\]"}