---
title: "Revenue and Expenses"
---

This page contains steps on how to prepare key account related to items on the income statement, such as revenue and expenses, and how their transactions are recorded. The content in this section is a part of the **Accounting Fundamentals** (certificate level) for the ACA qualification.

-   Note: for depreciation and disposals, see [Inventory and NCA](asset.qmd).

<br />

------------------------------------------------------------------------

# **Sales**

### Returns

During business, returns will occur. The accounting of returns is simple - we just reverse the original transaction.

::: panel-tabset
## Customer Returns

+------------------------------------------------------------+---------------------+
| 1\) Original Customer Purchase                             | Dr Cash/Receivables |
|                                                            |                     |
|                                                            | Cr Revenue          |
+------------------------------------------------------------+---------------------+
| 2\) Customer Returns: we reverse the original transaction. | Dr Revenue          |
|                                                            |                     |
|                                                            | Cr Cash/Receivables |
+------------------------------------------------------------+---------------------+

: {.bordered .sm tbl-colwidths="\[50,50\]"}

## You Return to Supplier

+-------------------------------------------------------------------+------------------+
| 1\) Your Original Purchase                                        | Dr Purchases     |
|                                                                   |                  |
|                                                                   | Cr Cash/Payables |
+-------------------------------------------------------------------+------------------+
| 2\) Your Return to Supplier: we reverse the original transaction. | Dr Cash/Payables |
|                                                                   |                  |
|                                                                   | Cr Purchases     |
+-------------------------------------------------------------------+------------------+

: {.bordered .sm tbl-colwidths="\[50,50\]"}
:::

<br />

### Discounts

Discounts at the time of sale (like bulk-order discounts) are just recorded as normal transactions at their discounted price.

However, some discounts take effect later, especially with credit sales and prompt payment. For example, you might offer a customer a 5% discount if they pay within a week. You will have some expectation of whether or not the customer/or you will take the discount.

At the moment of transaction, record the sale/purchase with the **expected price**. Then, if the **actual price** later with/without the discount is different than expected, you will need to adjust.

-   If the expected price and actual price are the same, no adjustment is needed.

::: panel-tabset
## Discount to Customer

+------------------------------------------------------+---------------------------------------------------+
| 1\) Initially record credit sale with expected price | Dr Receivables: Expected Price                    |
|                                                      |                                                   |
|                                                      | Cr Revenue: Expected Price                        |
+------------------------------------------------------+---------------------------------------------------+
| 2\) Record adjustment after actual price             | Cr Receivables: Expected Price                    |
|                                                      |                                                   |
|                                                      | Dr Cash: Actual Amount Customer Paid              |
|                                                      |                                                   |
|                                                      | Dr/Cr Revenue: The balancing figure to make Dr=Cr |
+------------------------------------------------------+---------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[50,50\]"}

Basically: initially, record expected price. Once paid, clear receivables account, record cash inflow, and balance with Dr/Cr in revenue.

## My Discount from Supplier

+----------------------------------------------------------+-----------------------------------------------------+
| 1\) Initially record credit purchase with expected price | Dr Purchases: Expected Price                        |
|                                                          |                                                     |
|                                                          | Cr Payables: Expected Price                         |
+----------------------------------------------------------+-----------------------------------------------------+
| 2\) Record adjustment after actual price                 | Dr Payables: Expected Price                         |
|                                                          |                                                     |
|                                                          | Cr Cash: Actual Price                               |
|                                                          |                                                     |
|                                                          | Dr/Cr Purchases: The balancing figure to make Dr=Cr |
+----------------------------------------------------------+-----------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[50,50\]"}

Basically: initially, record expected price. Once paid, clear payables account, record cash outflow, and balance with Dr/Cr in revenue.
:::

<br />

### Output VAT

When we sell a product to customers, they will pay us:

1.  The price of the product we are selling (exclusive of VAT price)
2.  The VAT (sales tax) of the product. This will need to be paid to HMRC.

We first need to figure out the price of the product (exclusive of VAT), and the VAT amount. Then, we can do the following transactions:

+----------------------------------------+---------------------------------------------+
| 1\) Sale Price to record for Revenue   | Dr Cash/Receivables: Exclusive of VAT Price |
|                                        |                                             |
|                                        | Cr Revenue: Exclusive of VAT Price          |
+----------------------------------------+---------------------------------------------+
| 2\) Record VAT and have to pay to HMRC | Dr Cash/Receivables: VAT Amount             |
|                                        |                                             |
|                                        | Cr VAT Payable (Liability): VAT Amount      |
+----------------------------------------+---------------------------------------------+

: {.bordered .sm tbl-colwidths="\[50,50\]"}

We can also combine the two into one transaction by combining the Dr Cash/Receivables entry:

-   Dr Cash/Receivables: inclusive of VAT Price.
-   Cr Revenue: Exclusive of VAT Price.
-   Cr VAT Payable: VAT amount.

Note: VAT is not an expense. We are simply acting as tax collectors for HMRC, so we never "gain control" of VAT, so we are not expensing it either.

<br />

### Input VAT

When we buy things from suppliers, we are paying for both the inventory, and the VAT of that inventory.

As a business (that is VAT registered with HMRC), we can reclaim this input VAT. This is money HMRC owe to us (but is still included in VAT payables liability account, but as a negative liability).

We first need to figure out the price of the product (exclusive of VAT), and the VAT amount. Then, we can do the following transactions:

+--------------------------------------------+------------------------------------------+
| 1\) Purchase Price to record for purchases | Dr Purchases: Exclusive of VAT Price     |
|                                            |                                          |
|                                            | Cr Cash/Payables: Exclusive of VAT Price |
+--------------------------------------------+------------------------------------------+
| 2\) Record Input VAT that HMRC owes to us  | Dr VAT Payables: VAT Amount              |
|                                            |                                          |
|                                            | Cr Cash/Payables: VAT Amount             |
+--------------------------------------------+------------------------------------------+

: {.bordered .sm tbl-colwidths="\[50,50\]"}

We can also combine the two into one transaction by combining the Dr Cash/Receivables entry:

-   Cr Cash/Receivables: inclusive of VAT Price.
-   Dr Purchases: Exclusive of VAT Price.
-   Dr VAT Payable: VAT amount.

<br />

### Deferred Income

We are selling a good/service. Let say we will provide the good/service in Year 2, but we require customers **prepay** in Year 1.

In accrual accounting, revenue is recognised when the **goods/services are in the control of the customer**. Thus, if we recorded this transaction as revenue in Year 1, we actually need to adjust our accounts so that the revenue occurs in Year 2.

+--------------------------------------------------------------------------------------------------------------------+----------------------------------+
| 1\) **Year 1**: the customer prepays. We record the following:                                                     | Cr Revenue X                     |
|                                                                                                                    |                                  |
|                                                                                                                    | Dr Cash X                        |
+--------------------------------------------------------------------------------------------------------------------+----------------------------------+
| 2\) **End of Year 1**: we realise goods/services are for Year 2. Thus, we need to take it out of Year 1's revenue. | Dr Revenue X                     |
|                                                                                                                    |                                  |
|                                                                                                                    | Cr Deferred Income (Liability) X |
+--------------------------------------------------------------------------------------------------------------------+----------------------------------+
| 3\) **Beginning of Year 2**: we now credit the revenue to Year 2.                                                  | Cr Revenue X                     |
|                                                                                                                    |                                  |
|                                                                                                                    | Dr Deferred Income (Liability) X |
+--------------------------------------------------------------------------------------------------------------------+----------------------------------+

: {.bordered .sm tbl-colwidths="\[50,50\]"}

Note: you can do partial adjustments. For example, if a customer prepays in Year 1 for 3 months of service in Year 1 and 4 months of service for Year 2, only the 4 months in Year 2 are deferred income.

Tip: Year-end balance of deferred income is **next year's** income.

<br />

### Accrued Income

We are selling a good/service. Let say we will provide the good/service in Year 1, but we require customers **pay later (arrears)** in Year 2.

In accrual accounting, revenue is recognised when the **goods/services are in the control of the customer**. Thus, we need to record this revenue in Year 1, even if no payment has occured

+--------------------------------------------------------------------------------------------------------------------+-----------------------------+
| 1\) **End of Year 1**: no payment has occurred, but we need to add revenue to Year 1.                              | Cr Revenue X                |
|                                                                                                                    |                             |
|                                                                                                                    | Dr Accrued Income (Asset) X |
+--------------------------------------------------------------------------------------------------------------------+-----------------------------+
| 2\) **Beginning of Year 2**: clear the accrued income balance.                                                     | Cr Accrued Income (Asset) X |
|                                                                                                                    |                             |
|                                                                                                                    | Dr Revenue X                |
+--------------------------------------------------------------------------------------------------------------------+-----------------------------+
| 3\) **Year 2**: the customer pays. We record this normally, so the Cr Revenue X cancels out step 2's Dr Revenue X. | Cr Revenue X                |
|                                                                                                                    |                             |
|                                                                                                                    | Dr Cash X                   |
+--------------------------------------------------------------------------------------------------------------------+-----------------------------+

: {.bordered .sm tbl-colwidths="\[50,50\]"}

Note: you can do partial adjustments. For example, if a customer pays after in Year 2 for 3 months of service in Year 1 and 4 months of service for Year 1, only the 3 months in Year 1 are accrued income.

Tip: year end balance of accrued income is **this year's** income.

<br />

<br />

------------------------------------------------------------------------

# **Expenses**

### Prepayments

We are buying a good/service (ex. utilities). Let say we will get the good/service in Year 2, but we **prepay** in Year 1.

The matching principle says we should match expenses to the revenue they generated. We used this good/service provided in Year 2 to generate revenues in Year 2. Thus, if we recorded this transaction as an expense in Year 1, we actually need to adjust our accounts so that the expense occurs in Year 2.

+--------------------------------------------------------------------------------------------------------------------+--------------------------+
| 1\) **Year 1**: We prepay. We record the following at the time of payment:                                         | Dr Expense X             |
|                                                                                                                    |                          |
|                                                                                                                    | Cr Cash X                |
+--------------------------------------------------------------------------------------------------------------------+--------------------------+
| 2\) **End of Year 1**: we realise expense should be for Year 2. Thus, we need to take it out of Year 1's expenses. | Cr Expense X             |
|                                                                                                                    |                          |
|                                                                                                                    | Dr Prepayments (Asset) X |
+--------------------------------------------------------------------------------------------------------------------+--------------------------+
| 3\) **Beginning of Year 2**: we now credit the expense to Year 2.                                                  | Dr Expense X             |
|                                                                                                                    |                          |
|                                                                                                                    | Cr Prepayments (Asset) X |
+--------------------------------------------------------------------------------------------------------------------+--------------------------+

: {.bordered .sm tbl-colwidths="\[50,50\]"}

Note: you can do partial adjustments. For example, if we prepay in Year 1 for 3 months of service in Year 1 and 4 months of service for Year 2, only the 4 months in Year 2 are prepaid.

<br />

### Accrued Expense

We are buying a good/service. Let say we will get the good/service in Year 1, but we **pay later** in Year 2.

The matching principle says we should match expenses to the revenue they generated. We used this good/service provided in Year 1 to generate revenues in Year 1. Thus, we need to record this expense in Year 1, even if no payment has occurred.

+---------------------------------------------------------------------------------------------------------+-----------------------------------+
| 1\) **End of Year 1**: no payment has occurred, but we need to add expense to Year 1.                   | Dr Expense X                      |
|                                                                                                         |                                   |
|                                                                                                         | Cr Accrued Expenses (Liability) X |
+---------------------------------------------------------------------------------------------------------+-----------------------------------+
| 2\) **Beginning of Year 2**: clear the accrued expenses balance.                                        | Dr Accrued Expenses (Liability) X |
|                                                                                                         |                                   |
|                                                                                                         | Cr Expense X                      |
+---------------------------------------------------------------------------------------------------------+-----------------------------------+
| 3\) **Year 2**: we pay. We record this normally, so the Dr Expense X cancels out step 2's Cr Expense X. | Dr Expense X                      |
|                                                                                                         |                                   |
|                                                                                                         | Cr Cash X                         |
+---------------------------------------------------------------------------------------------------------+-----------------------------------+

: {.bordered .sm tbl-colwidths="\[50,50\]"}

Note: you can do partial adjustments. For example, if we pay after in Year 2 for 3 months of service in Year 1 and 4 months of service for Year 1, only the 3 months in Year 1 are accrued expenses.

<br />

### Cost of Sales

The cost of sales is the cost of the inventory (goods sold) that generated the revenue/sales of that period.

+-----------------------------------+-----------------------------------+
| Opening Inventory                 | £X                                |
|                                   |                                   |
| Purchases (net, if returns exist) | £X                                |
|                                   |                                   |
| Inward Delivery Costs             | £X                                |
|                                   |                                   |
| (less) Closing Inventory          | (£X)                              |
+-----------------------------------+-----------------------------------+
| **Cost of Sales**                 | **£X**                            |
+-----------------------------------+-----------------------------------+

: {.bordered .sm tbl-colwidths="\[50,50\]"}

There are two types of delivery expenses that might be incurred, which have to be recorded differently.

+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| Delivery Inwards                                                                                | Delivery Outwards                                                                               |
+=================================================================================================+=================================================================================================+
| Delivery costs and expenses to deliver products [from suppliers to your inventory.]{.underline} | Delivery costs and expenses to deliver products from [your inventory to customers]{.underline}. |
+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| This will be included/added as an expense within the **cost of sales**.                         | This is a separate expense in the **operating/administration expenses**.                        |
+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[50,50\]"}

<br />

### Payroll Expense

When a firm pays its employees, it has to pay 3 things:

1.  Employee's income tax to the tax collector (HRMC in the UK).
2.  Employee's national insurance contribution (and the employer's additional contribution) to the tax collector.
3.  Employee the remaining net salary.

The net income to the employee is paid immediately (such as at the end of the month), but the tax and national insurance is usually withheld until tax filling season.

+--------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| **Dr Wages (Expense)**         | gross wages + employer national insurance             | This expense covers net salary, income tax, and employee [+ employer national insurance contribution]{.underline}. |
+--------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| **Cr Cash (Asset)**            | net wages                                             | The cash of net income that is paid out to the employee.                                                           |
+--------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| **Cr Tax Payable (Liability)** | income tax + employee and employer national insurance | Taxes are paid at the end of the year, so there is a liability for income tax and national insurance.              |
+--------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[30,30,40\]"}

When the tax is later paid to the tax authority (HMRC), the liability is reduced (debited) and cash is decreased (credited).

<br />

### Margin and Markup

Margin and markup are two relationships between the sales, cost of sales, and gross profit. They often inform companies and investors about the profitability of a firm.

**Margin** is the ratio of the gross profit to sales (revenue):

$$
\text{margin} = \frac{\text{gross profit}}{\text{revenue}}
$$

**Markup** is defined as the ratio of the gross profit to sales, and can also be determined by a ratio of sales to cost of sales:

$$
\text{markup} = \frac{\text{gross profit}}{\text{cost of sales}} \quad \text{or} \quad 1 + \text{markup} = \frac{\text{sales}}{\text{cost of sales}}
$$

<br />

### Irrecoverable Debt

When a firm makes a credit sale, they will increase their receivables balance. This is a debt that the customer owes to the firm.

Sometimes, the firm will believe the customer will never pay (ex. bankrupt, fled the country). This is now an irrecoverable debt that needs to be removed from receivables since it is no longer expected to be received.

+----------------------------------------------------------------------+---------------------------------------+
| 1\) Original credit sale                                             | Cr Revenue X                          |
|                                                                      |                                       |
|                                                                      | Dr Receivables X                      |
+----------------------------------------------------------------------+---------------------------------------+
| 2\) Irrecoverable debt adjustment: get rid of debt from receivables. | Dr Irrecoverable Debt Expense (IDE) X |
|                                                                      |                                       |
|                                                                      | Cr Receivables X                      |
+----------------------------------------------------------------------+---------------------------------------+

: {.bordered .sm tbl-colwidths="\[50,50\]"}

Irrecovarable Debt Expense (IDE) is an administrative/operating expense for the income statement.

It is also possible that after writing off a debt, somehow, it is still payed by the customer. The following entry would be required:

+-----------------------------------------------------+----------------------------------------+
| 3\) Irrecoverable debt recovered: clear IDE account | Dr Cash X                              |
|                                                     |                                        |
|                                                     | Cr Irrecovrerable Debt Expense (IDE) X |
+-----------------------------------------------------+----------------------------------------+

: {.bordered .sm tbl-colwidths="\[50,50\]"}

<br />

### Doubtful Debt

In accounting, we are prudent/conservative. Thus, if there is a possibility a debt will not be paid, we need to show this in financial statements.

At the **end of the year**, an allowance for doubtful debt is set up. This is basically an amount that we believe will have a chance of not being paid.

-   Allowance is often calculated as a percentage (ex. 50% chance £1,000 will not be paid, so £500 allowance). However, this amount usually given in questions.

+--------------------------+--------------------------------------------+
| 1\) Original credit sale | Cr Revenue X                               |
|                          |                                            |
|                          | Dr Receivables X                           |
+--------------------------+--------------------------------------------+
| 2\) Set up allowance     | Cr Allowance for Receivables (Liability) X |
|                          |                                            |
|                          | Dr Irrecoverable Debt Expense (IDE) X      |
+--------------------------+--------------------------------------------+

: {.bordered .sm tbl-colwidths="\[50,50\]"}

The allowance for receivables is a **liability** (negative asset) that reduces the value of the Receivables. Thus, gross receivables minus allowance equals net receivables.

**Allowance is set at the end of the year**. Note that allowances are often determined at a certain value, so the double entry **should not be the value of the allowance**, but the **amount change** to go from the old allowance value to the new allowance value.

-   Ex. if last year's allowance is £500, and this year's is £800, we should only Cr Allowance £300 (the change).

<br />

### Provisions

<br />

### Corporation Tax

Only incorporated companies pay corporation tax. Sole traders and partners simply pay income tax on their profits.

The corporate tax cycle is as follows for tax incurred on profits in Year 1:

+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------+
| 1\) **End of Year 1**: Corporate tax is estimated. A liability for the estimated tax is created.                                                                                              | Dr Tax Expense: Estimated Amount             |
|                                                                                                                                                                                               |                                              |
|                                                                                                                                                                                               | Cr Tax Payable (Liability): Estimated Amount |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------+
| 2\) **Year 2**: tax return is submitted by company. The **actual tax amount** may be different than the estimated amount.                                                                     |                                              |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------+
| 3\) **Year 2:** you pay the actual amount to HMRC                                                                                                                                             | Cr Cash: Actual Amount                       |
|                                                                                                                                                                                               |                                              |
|                                                                                                                                                                                               | Dr Tax Payable: Actual Amount                |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------+
| 4\) **Year 2:** If the estimated and actual tax amount are different, there will be a remaining balance on the payable account. Clear the balance and assign it to this year 2's tax expense. | Dr/Cr Tax Payable: Leftover Amount           |
|                                                                                                                                                                                               |                                              |
|                                                                                                                                                                                               | Cr/Dr Tax Expense: Leftover Amount           |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------+

: {.bordered .sm tbl-colwidths="\[50,50\]"}

-   An **underprovision** is when the estimated tax amount is lower than the actual tax amount. A Dr balance will be left of the payable account after paying.
-   An **overprovision** is when the estimated tax amount is higher than the actual tax amount. A Cr balance will be left on the payable account after paying.

Tip: At the end of any period:

-   Tax Payable balance is always the **estimated tax for that year**.
-   Tax expense balance is the estimated tax for that year **+/- leftover amount** from underprovision/overprovision.

<br />