---
title: "Assurance Basics"
---

This page covers the basics of assurance, ethical codes, and obtaining/accepting an assurance engagement. The content in this section is a part of the **Assurance and Risk Fundamentals** (certificate level) for the ACA qualification.

<br />

------------------------------------------------------------------------

# **Introduction to Assurance**

### Elements of Assurance

Assurance is when an independent professional (auditor) examines statements of a firm, to assure investors and stakeholders of the accuracy of the information, allowing them to make choices.

+------------------------------+---------------------------------------------------------------------------------------------------+
| **Statutory Audit**          | Auditing of financial statements, governed by accounting standards and reporting regulations.     |
+------------------------------+---------------------------------------------------------------------------------------------------+
| **Sustainability Assurance** | Auditing of a firm's sustainability figures and reports.                                          |
+------------------------------+---------------------------------------------------------------------------------------------------+
| **Other Assurance**          | Due diligence before performing transactions, internal controls assessment, fraud investigations. |
+------------------------------+---------------------------------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[30,70\]"}

There are three parties in any assurance engagement:

+-----------------------+----------------------------------------------------------------------------------------------------------------+
| **Practitioner**      | The auditor or independent professional.                                                                       |
+-----------------------+----------------------------------------------------------------------------------------------------------------+
| **Responsible Party** | The directors/management of the firm being audited.                                                            |
+-----------------------+----------------------------------------------------------------------------------------------------------------+
| **Intended User**     | Stakeholders (shareholders, investors, banks, etc.) that may need details on the firm's financial performance. |
+-----------------------+----------------------------------------------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[30,70\]"}

::: {.callout-note collapse="true" appearance="simple"}
## Benefits and Limitations of Assurance

Benefits:

-   Independent scrutiny of the business by experts, which adds credibility to the firm's financial statements.
-   Can help deter the appeal of fraud for those in the firm.
-   Draws attention to issues, such as ethical issues or weaknesses of internal controls.
-   Reduces risk of management bias.

Limitations:

-   Assurance does not provide 100% assurance for accuracy, since you cannot possibly test and check every transaction made by a firm (especially large firms).
-   Cannot solve potential issues of collusion fraud between auditors and companies.
-   Financial information often includes subjective matters, such as depreciation and provision for doubtful debts.
-   May rely on some sub-optimal evidence, such as management representations.
:::

<br />

### Levels of Assurance

Usually, when considering the accuracy of financial statements, auditors are concerned with **materiality**.

> **A mistake is material if its omission or misstatement could influence the economic decisions of users of the report.**

::: {.callout-note collapse="true" appearance="simple"}
## Materiality, Error, and Fraud

-   For example, for a \$10 billion net profit business, a \$1 mistatement is not substantial enough to influence the economic decisions of users of the report, so it is not material. However, a \$1 billion mistatement could quite substantially change how users use the report.
-   The threshold of materiality is often set at some percentage of net income before tax (ex. 5%) or revenue (1-2%).
-   There is also a distinction between **Error** and **Fraud**. Error is considered a genuine mistake of the responsible party. Fraud is [intentional]{.underline}: someone deliberately provides false information to mislead users.
:::

At the end of an engagement, the auditor needs to write an **opinion** on the level of assurance they can assure regarding the accuracy of the financial statements.

+---------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
| Reasonable Assurance                                                      | Limited Assurance                                                                                                      |
+===========================================================================+========================================================================================================================+
| High level of assurance of accuracy, but not absolute.                    | Moderate/low level of assurance of accuracy.                                                                           |
+---------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
| Conclusion expressed **positively**.                                      | Conclusion expressed **negatively**.                                                                                   |
+---------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
| > **In our opinion, the financial statements show a true and fair view.** | > **Nothing has come to our attention that causes us to believe that the financial information is not true and fair.** |
+---------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
| Used in statutory audits.                                                 | Used in all other engagements.                                                                                         |
+---------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[50,50\]"}

::: {.callout-note collapse="true" appearance="simple"}
## The Expectations Gap

Users and the public often misinterpret audit opinions to mean other things. This "expectation" of the public contrasting with what audit opinions actually claim is called the expectations gap.

+------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Public                                                                                                     | Reality                                                                                                                                                                                                        |
+============================================================================================================+================================================================================================================================================================================================================+
| The public often thinks the auditor detects all fraud and error.                                           | This is not true, the auditor only provides reasonable assurance, not absolute assurance.                                                                                                                      |
+------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| The public often thinks auditors test 100% of transactions.                                                | This is not true, most audits sample transactions to test.                                                                                                                                                     |
+------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| The public often thinks auditors guarantee the accuracy of financial statements.                           | This is not true, the auditor only provides reasonable assurance, not absolute assurance.                                                                                                                      |
+------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| The public often thinks auditors guarantee the company will continue to survive for the forseeable future. | This is not true, the auditor only provides an opinion of the accuracy of financial statements. The financial statements themselves can paint a good or bad picture, the auditor only cares if it is accurate. |
+------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| The public often thinks the balance sheet shows the true value of the company.                             | This is not true, valuation is done by separate teams.                                                                                                                                                         |
+------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[50,50\]"}
:::

<br />

### Legal Requirements

In the UK, all companies are required to undergo a statutory audit of their financial statements every year, *unless* they meet a set of exemption criteria from **Companies Act 2006**.

To qualify for an exemption, a firm must **not** be an insurance, banking, or listed company.

In addition, they must also meet two of the following exemption critera below:

-   Firms that are in banking, insurance, or listed on a stock market **must** always undergo a statutory audit, even if they meet the criteria below.

+----------------------------------------+----------------------------------------+
| Exemption After 6 April 2025 (2/3)     | Exemption After 1 January 2016 (2/3)   |
+========================================+========================================+
| **Less** than 50 employees on average. | **Less** than 50 employees on average. |
+----------------------------------------+----------------------------------------+
| **Less** than £7.5m in total assets.   | **Less** than £5.1m in total assets.   |
+----------------------------------------+----------------------------------------+
| **Less** than £15m in turnover.        | **Less** than £10.2m in turnover.      |
+----------------------------------------+----------------------------------------+

: {.bordered .sm tbl-colwidths="\[50,50\]"}

<br />

### Sustainability Assurance

Sustainability consists of **environmental, social, and governance (ESG)** considerations.

+---------------------------------------------------------+----------------------------------------------------------------------------+-------------------------------------+
| Environmental                                           | Social                                                                     | Governance                          |
+=========================================================+============================================================================+=====================================+
| About the planet. For example, emissions and pollution. | About the people. Diversity, inclusion, worker health, mental health, etc. | About company practices and ethics. |
+---------------------------------------------------------+----------------------------------------------------------------------------+-------------------------------------+

: {.bordered .sm tbl-colwidths="\[33,34,33\]"}

Different standards regarding sustainability reporting and assurance:

+--------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
| **IFRS International Sustainability and Standards Board (ISSB)**   | International objectives for sustainability standards (not legally required)                                          | -   Standards for a global baseline of sustainability disclosures.                                                                          |
|                                                                    |                                                                                                                       | -   Meet information need of investors.                                                                                                     |
|                                                                    |                                                                                                                       | -   Enable firms to provide sustainability information to capital markets.                                                                  |
|                                                                    |                                                                                                                       | -   Interoperability with jurisdiction-specific regulations and disclosures                                                                 |
+--------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
| **Companies Act 2006 (UK)**                                        | Mandatory sustainability reporting requirements (for UK)                                                              | -   Report the principal risks and uncertainties facing a firm, including sustainability risks.                                             |
|                                                                    |                                                                                                                       | -   Report info about ESG matters, employees, gender diversity, respect for human rights, anti-corruption, and anti-bribery.                |
|                                                                    |                                                                                                                       | -   Climate related financial disclosures: ex. climate adjacent risks and opportunities.                                                    |
+--------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
| **Task Force on Climate-Related Financial Disclosures (TCFD)**     | Recomendations for sustainability reporting, but mandatory for listed companies in UK.                                | -   Report on governance, risk management, strategy, and metrics and targets.                                                               |
|                                                                    |                                                                                                                       | -   IFRS S2 reporting standards are based on these recommendations.                                                                         |
+--------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
| **Corporate Sustainability Reporting Directive (CSRD)**            | Mandatory requirements for listed EU companies and large EU companies and Non-EU companies with large revenues in EU. | -   Disclosure on company's sustainability related impacts, risks, and opportunities.                                                       |
|                                                                    |                                                                                                                       | -   Discolsures should be included in annual report of a company.                                                                           |
|                                                                    |                                                                                                                       | -   Requires assurance over sustainability disclosures.                                                                                     |
+--------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
| **International Standard on Sustainability Assurance (ISSA) 5000** | Framework for sustainability assurance engagements.                                                                   | -   Basically, tries to make sustainability assurance like statutory audit: an opinion (reasonable or limited) and a conclusion with basis. |
+--------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[25,25,50\]"}

<br />

<br />

------------------------------------------------------------------------

# **Professional Ethics**

### Ethical Codes

There are a few main regulatory bodies in the UK:

+---------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **ICAEW** (Institute of Chartered Accountants in England and Wales) | Sets the code of ethics for member auditors/accountants. The ICAEW code is based on the internal code of ethics established by the IESBA.                                                                                             |
+---------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **FRC** (Financial Reporting Council)                               | Oversees auditors, sets the ethical standards for audit work, and supervises corporate governance and financial reporting bodies. The FRC also has a professional oversight function.                                                 |
+---------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **IESBA** (International Ethics Standards Board for Accountants)    | Develops the international code of ethics for auditors/accountants, which serves as the foundation for the ICAEW ethics code.                                                                                                         |
+---------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Recognised Supervisory Bodies**                                   | Organisations like ICAEW that supervise auditors, and ensure compliance with ethical and professional standards. These bodies work together to set, monitor, and enforce ethical standards, ensuring public trust in audits/auditors. |
+---------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[30,70\]"}

The ethical codes that these bodies set can be divided into two types:

+---------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Rule-Based Codes**      | Specific, detailed requirements, like a checklist of what is and isn't allowed.                                                                                                    |
|                           |                                                                                                                                                                                    |
|                           | Ex. no gifts over £30.                                                                                                                                                             |
+---------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Principle Based Codes** | Broad principles that guide behaviour for a wide range of professional situations. Docus more on professional judgment rather than spelling out rules for every possible scenario. |
|                           |                                                                                                                                                                                    |
|                           | Ex. no gifts that could impair your objectivity (no specific max value). This is used by the ICAEW and IESBA, since they are more flexible and adaptable to new situations.        |
+---------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[30,70\]"}

<br />

### Ethical Principles

ICAEW's ethics code is mostly principle-based, but also has some specific rule-based codes for specific things. There are 5 fundamental ethical principles for ICAEW:

+------------------------------------------+-----------------------------------------------------------------------------------------------------------------------+
| **Integrity**                            | Be honest and straight forward.                                                                                       |
+------------------------------------------+-----------------------------------------------------------------------------------------------------------------------+
| **Objectivity**                          | To not allow bias, conflict of interest, or undue influence to affect your business judgment.                         |
+------------------------------------------+-----------------------------------------------------------------------------------------------------------------------+
| **Professional Competence and Due Care** | Maintain your skills and knowledge to provide a competent service, and act in accordance with professional standards. |
+------------------------------------------+-----------------------------------------------------------------------------------------------------------------------+
| **Confidentiality**                      | Respect confidentiality of information, do not disclose without proper authority.                                     |
+------------------------------------------+-----------------------------------------------------------------------------------------------------------------------+
| **Professional Behaviour**               | Comply with rules and regulations, avoid conduct that would discredit the occupation.                                 |
+------------------------------------------+-----------------------------------------------------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[30,70\]"}

**Independence** is key to objectivity. [Independence of mind]{.underline} is the ability to make decisions free from bias or influence. [Independence in appearance]{.underline} is avoiding situations that may make a third party doubt your impartiality, even if you are already not biased.

::: {.callout-note collapse="true" appearance="simple"}
## More on Independence

Independence is not necessarily threatened if auditors use the client's services, **given** the prices/services the auditors are using are also available to the public.

-   Ex. Auditors can have mortgages with a bank they are auditing, as long as those mortgages and rates are publicly available, and the mortgage was obtained prior to the engagement.
-   However, if the bank, after learning of the auditor's appointment, provides favourable mortgages to the auditors and only the auditors, then it is a conflict of interest.
:::

::: {.callout-note collapse="true" appearance="simple"}
## Types of Biases

+----------------------+--------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Bias                 | Description                                                                                | Example                                                                                                                                      |
+======================+============================================================================================+==============================================================================================================================================+
| Anchoring Bias       | Tendency to use an initial piece of information, which subsequent information is assessed. | Say an item was \$50, but now is on sale for \$30. \$30 might still be an overpay, but in the context of the original price, it seems cheap. |
+----------------------+--------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Automation Bias      | Tendency to blindly trust output generated from automated systems.                         | Blindly trusting the output from accounting software.                                                                                        |
+----------------------+--------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Availability Bias    | Putting more weight on experiences that easily come to mind.                               | We tend to think of plane crash news stories far more than the millions who have safe plane journeys.                                        |
+----------------------+--------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Confirmation Bias    | Disregarding information that does not fit our existing beliefs.                           | Common in politics.                                                                                                                          |
+----------------------+--------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Groupthink           | Tendency for groups to reach a conclusion without critical reasoning.                      | Social media like Reddit.                                                                                                                    |
+----------------------+--------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Overconfidence Bias  | Overestimating one's own abilities.                                                        | If you are experienced, you might not check your work as carefully and assume it is correct.                                                 |
+----------------------+--------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Representation Bias  | Assuming the interactions/experiences you have are representative of all people.           |                                                                                                                                              |
+----------------------+--------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Selective Perception | Expectations influencing personal views.                                                   | If you expect something to be bad, you are more likely to look for the bad parts.                                                            |
+----------------------+--------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[20,35,45\]"}
:::

<br />

### Threats and Safeguards

There are several common threats to ethical behaviour:

+---------------------------------+----------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Threat                          | Description                                                                                                                      | Safeguards                                                                                                                                                                        |
+=================================+==================================================================================================================================+===================================================================================================================================================================================+
| **Self-Interest Threat**        | Financial or personal interest that may affect your judgment/bias.                                                               | -   Make sure no audit team members have shares.                                                                                                                                  |
|                                 |                                                                                                                                  | -   No accepting gifts unless very small in value.                                                                                                                                |
|                                 | Ex. owning shares in a company you are auditing, or one client making up a large proportion of fees for your auditing firm.      | -   Listed company's audit fees should make no more than 10% of the audit firm's income, and needs to be disclosed if exceeds 5% (Add 5% to thresholds for non-listed companies). |
+---------------------------------+----------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Self-Review Threat**          | Reviewing your own work, or work by your team, previously did.                                                                   | -   Accounting services can only be offered if the services and audit are 2 separate teams, and work is mechanical/technical.                                                     |
|                                 |                                                                                                                                  | -   Tax calculations and valuations cannot be offered by the audit firm if the client is listed.                                                                                  |
|                                 | Ex. auditing financial statements that you yourself produced.                                                                    |                                                                                                                                                                                   |
+---------------------------------+----------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Advocacy Threat**             | When you promote a clients position to a point where your objectivity is compromised.                                            | -   Audit firm is not allowed to promote, deal in, or underwrite a client's shares.                                                                                               |
|                                 |                                                                                                                                  | -   Audit firm cannot provide legal services in a legal case to the client.                                                                                                       |
|                                 | Ex. representing a firm in a legal dispute, yet also auditing them.                                                              |                                                                                                                                                                                   |
+---------------------------------+----------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Familiarity Threat**          | Having a long standing or close relationship with the client, making you more sympathetic.                                       | -   **Audit rotation**: for listed companies, lead partner of audit must change every 5 years (can extend to 7 years in exceptional cases), and cannot return for 5 years.        |
|                                 |                                                                                                                                  | -   Audit employees with personal relationships with client should not be on audit.                                                                                               |
|                                 | Ex. you are auditing a company which has your best friend as financial director.                                                 |                                                                                                                                                                                   |
+---------------------------------+----------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Intimidation Threat**         | Deterred from acting objectively by external pressures.                                                                          | -   If partner of audit firm joins client, the firm should resign as auditor, and cannot take the audit for 2 years.                                                              |
|                                 |                                                                                                                                  | -   Audit employees with personal relationships with client should not be on audit team.                                                                                          |
|                                 | Ex. the client threatens to replace you as auditor if you do not provide favourable audit.                                       |                                                                                                                                                                                   |
+---------------------------------+----------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Management Threat** (UK Only) | When you or your firm that influences client management decisions, and your interests become aligned with the client management. | -   Use the engagement letter to limit the involvement of the audit firm away from management.                                                                                    |
|                                 |                                                                                                                                  | -   Regulations saying consultants cannot be auditor.                                                                                                                             |
|                                 | Ex. you do consulting services for a client that influences their management decisions, then you audit them.                     |                                                                                                                                                                                   |
+---------------------------------+----------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[18,39,43\]"}

<br />

### Data Protection (GDPR)

General Data Privacy Regulations (GDPR) in the UK and EU restrict the way auditors can collect and store data.

-   Auditors (and anyone) who processes personal information must ensure it is protected.
-   Individuals hve a right to access their personal data, and information on how it is being processed.
-   Individual data can only be held if the individual has opted in, or there is a specific legal duty.

Disclosure of information is divided into two ways: right to disclose and duty to disclose.

+----------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------+
| Right to Disclose                                                                      | Duty to Disclose                                                                    |
+========================================================================================+=====================================================================================+
| You have the option to disclose private information if the following conditions apply. | You **must** disclose private information if any of the following conditions apply. |
+----------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------+
| -   Client has given permission.                                                       | -   Suspicions of money laundering.                                                 |
| -   Disclosure is in the "public interest".                                            | -   Suspicions of criminal activity.                                                |
| -   To defend the firm in a negligence claim.                                          | -   Quality review or investigation of a professional/regulatory body.              |
+----------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[50,50\]"}

<br />

<br />

------------------------------------------------------------------------

# **Agreeing an Engagement**

### Obtaining an Engagement

There are several ways to get clients for an audit engagement.

+--------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| **Tender**         | A client needs an auditor, and opens up a bidding process where multiple audit firms present offers. The client will then select an auditor. |
+--------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| **Advertise**      | Using advertisements to get clients.                                                                                                         |
|                    |                                                                                                                                              |
|                    | Note: you must stick to ethical guidelines. This includes not discrediting the profession.                                                   |
+--------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| **Recommendation** | A client of yours recommends your audit firm to another firm. They then become your client.                                                  |
+--------------------+----------------------------------------------------------------------------------------------------------------------------------------------+

: {.bordered .sm tbl-colwidths="\[30,70\]"}

However, before you agree to be the auditor, ensure that a few things have been met:

-   Ensure you are professional qualified to be auditor.
-   Ensure no legal or ethical reasons for you to not be the auditor.
-   Ensure you have adequate resources (staff, budget) to complete the audit.
-   If there is a previous auditor, the current practitioner must communicate with them, and determine if there are any reasons not to accept (like ethical concerns). Permission must be granted by the responsible party for this communication, but if this permission is denied, the audit is almost always refused by the practitioner.

<br />

### Audit Engagement Letters

After accepting an engagement, an engagement letter (contract) needs to be set up. his engagement letter should include:

1.  The extent of the auditor and management's responsibilities.
2.  The scope of the engagement, and the objectives of the audit.
3.  The form of the reports that will be issued, and what reporting framework.
4.  Level of access to books and records for evidence.
5.  Restrictiosn on the auditor's liability (if possible).
6.  Fees and how they are calculated.

The audit engagement letter serves as a contract that will minimise misunderstanding and ensure all parties know their roles in the audit.

<br />