---
title: "Internal Controls"
---

Internal controls are the policies and procedures put in place by management of a firm to comply with regulations and produce reliable financial statements. The content in this section is a part of the **Assurance and Risk Fundamentals** (certificate level) for the ACA qualification.

<br />

------------------------------------------------------------------------

# **Internal Controls**

### Systems of Controls

Internal controls are systems implemented and maintained by the management of a company (internally), to ensure financial reporting is reliable and accurately, the effectiveness and efficiency of operations, and compliance with applicable laws and regulation.

A good control system has a few principles:

1.  Controls must be designed to address specific risks. For example, unauthorised payments or errors in financial reporting.
2.  Controls should be implemented and operated consistently, not just on paper.
3.  Controls need to be monitored and updated as risks and business processes change.

Examples of controls include:

-   Quality control can prevent the production of poor quality goods.
-   Credit control can limit the level of bad debts
-   Controls over inventory can prevent running out of inventory and ensure optimal levels of inventory.
-   Compliance department can ensure business adheres to relevant laws and regulations.
-   Controls over payroll ensure salaries are paid correctly, avoiding disputes with staff, and avoiding mistakes over payroll taxes.

Auditors care about the internal controls, as it impacts the audit risk, and how we plan for an audit. Thus, auditors often take notes, confirm checklists, and diagram/flowchart internal controls. Walkthrough tests of controls are done to obtain information about them.

::: {.callout-note collapse="true" appearance="simple"}
## Limitations of Controls

-   Human error or intentional collusion which can bypass systems.
-   Abnormal/occasional transactions which may not fit into the control system.
-   Management override.
-   Informal nature/lack of documentation, especially in smaller companies.
-   Limited number of staff which limits segregation of duties.
-   The costs of controls may exceed the potential risks.
:::

<br />

### Components of Controls

A company's **control activities** are the policies/procedures that help ensure that management directives are carried out. They can be:

-   **Preventative controls**: preventing errors from occurring in the first place.
-   **Detective controls**: detecting errors/fraud that have already occurred.

Aside for control activities, there are also other aspects of a system of controls:

::: panel-tabset
## Activities

There are 5 types of different control activities (and an additional one), according to ISA (UK) 315:

1.  **Authorisation and approval** (preventative). Example: expenses require authorisation and approval (can be automated)
2.  **Reconcilliations** (detective): compare two or more data elements (ex. balances), and *match the balance* (nothing without matching/agreeing the balance is a reconciliation).
3.  **Verifications** (detective): verify something with another source of evidence (verify completeness/occurrence, not matching balances like reconciliation).
4.  **Physical/Logical controls** (preventative/detective): physical security (like locks, passwords), checks for the number of documents/invoices (logical true/false).
5.  **Segregation of duties** (preventative): assigning different people different parts of the same task, thus requiring multiple people to check/complete and preventing one person from committing fraud alone.
6.  **General IT Checks** which check machines work properly (antivirus, testing system processes), while **information processing controls** are IT versions of verification, reconciliation, and logical controls when dealing with info input.

## Environment

The **control environment** is the overall attitude, awareness, and actions of management regarding internal controls. This "sets the tone" for internal controls. Good environments can include:

-   Existence and frequent meeting of an audit committee, and an internal audit function.
-   Effective documentation of control systems, importance of controls communicated to all staff, and recruiting only employees integrity.
-   No management override of controls.

An audit committee (mandatory for listed companies) is a subsection of the board of directors. It has the following characteristics:

-   All members must be non-executive directors. The internal audit chief should not sit on the committee, as they are an executive director.
-   Required to have written terms of reference, which includes committee objectives and the format and content of reports to the board of directors.
-   Overseas the financial statement, internal audit, and external audit appointments.

## Risk Process

A company's **risk assessment process** is a process for identifying and anlaysing business risks.Business risks is a risk that could adversely effect a company's ability to achieve its objectives and execute its strategies.

-   Business risks can often impact inherent risk, a part of the Audit risk equation.

A risk assessment process should have the following steps:

1.  Identify relevant business risks, such as changes i noperating environment, new systems, rapid growth (international), new technology.
2.  Estimate the significance of the risks. Is it high, medium, or low?
3.  Assess the likelihood of the risk occuring.
4.  Decide on actions to address the risk.

## Information System

A company's **information system and communication** shows how information is correctly recorded, stored, and processed to ensure accurate record keeping and reporting.

This includes the financial reporting system, and how transactions are recorded and processed. Auditors are interested in things such as:

-   Classes of transactions (like types/categories they are saved in).
-   Systems used to prepare financial systems, such as accounting software.
-   Accounting records and information, such as invoices and receipts.
-   Roles and responsibilities allocated to staff - who can change things, who can input things, who can view things, and if there are dangers of controls being overridden.

## Monitoring

Ongoing or separate evaluations to ensure controls activities are working as intended.

-   Directors should assess if they are still adequate, especially when there are changes in the environment and business risks.
-   Controls should be monitored at all levels.
-   Internal audit can test controls, and recommend changes.
-   External audit can highlight deficiencies during the auditing process, that the directors can take and implement fixes.
:::

::: {.callout-note collapse="true" appearance="simple"}
## Emerging Technologies

To understand controls, an auditor must understand the technology the organisation is using in its processes, and the associated risks.

-   Robotic Process Autmoation (RPA) are automated processes that automate tasks based on "if this, then that" instructions. They are common for repetitive tasks. It is important to test if these systems are operating correctly.
-   Generative AI is also being used very commonly. However, we have to be concerned about the biases in AI, data privacy in training data, transparency behind AI decisions, and environmental impacts of AI. There should be controls and procedures to minimise these risks.
-   Cloud computing and storage, such as online storage or accounting records, are also vulnerable to risks such as data privacy and security, as well as data corruption. There should be controls over these risks, such as password changes and backup policies.
-   Digital signatures are also commonly used, but can be forged. Effective control systems will have logs and certificate of completion as controls.
-   Cybersecurity risks, such as attacks, are also a vulnerability.
:::

<br />

<br />

------------------------------------------------------------------------

# **Revenue System**

<br />

<br />

------------------------------------------------------------------------

# **Purchases System**

<br />

<br />

------------------------------------------------------------------------

# **Employee Costs**

<br />

<br />

------------------------------------------------------------------------

# **Internal Audit**

<br />

<br />

------------------------------------------------------------------------

<br />

### Internal Audit

Internal audit is an independent function in a firm, responsible for monitoring and reviewing the effectiveness of internal controls.

Internal auditers do not implement or design controls, as that is the job of management. Instead, they provide assurance to management and the board that controls are working correctly and as intended. The responsibilities of internal audit are:

1.  Testing whether controls are operating effectively.
2.  Reviewing the efficiency and effectiveness of operations.
3.  Checking compliance with laws, regulations, and company policies.
4.  Recommending improvements to controls and processes for management to action on.
5.  Assisting in fraud detection and risk management.

In smaller firms without an internal audit function, external auditors may perform the role of providing feedback on control weaknesses. However, the responsibility of monitoring (the other functions of internal audit) will be with the firm's management.

<br />

### Modern Controls

As organisations adopt new technologies, new risks emerge. Modern internal controls address these risks, including cyber security, supply chain management, and digital transformation.

-   **Cybersecurity**: these risks include human error (ex. weak passwords), fraud and deliberate sabotage, computer malware, DDos attacks. To mitigate these risks, firms often require strong password policies and frequent password changes, firewalls and anti-virus software, and access controls for authorised users only.
-   **Supply Chain Risks**: these risks include disruptions from supplier failure, nature disasters, and geopolitical events. To mitigate these risks, firms can vet and monitor suppliers, maintain alternative suppliers, reviewing supplier contracts regularly, and using tech to track supplies and shipments.
-   **Digital Transformation**: these risks from new tech include overreliance on tech, automation bias, and trusting systems without sufficient review. Controls include regular reviewing and testing of automated processes, maintaining manual checks for critical transactions, and training staff to interpret and question system outputs.

<br />