---
title: "Process of Assurance Engagements"
---

This page covers the general process of assurance and audit engagements, starting from planning, to concluding. The content in this section is a part of the **Assurance and Risk Fundamentals** (certificate level) for the ACA qualification.

<br />

------------------------------------------------------------------------

# **Audit Planning**

### Planning Process

Before starting an accepted engagement, there needs to be a plan. This helps preparing the neccesary resources (funding, team size, timeline) of the audit, as well as what areas are potentially higher risk for fraud/error.

There are two documents that are needed to plan an audit engagement.

1.  **Audit strategy**: Determines the scope, timing, and direction of the audit, and shapes the audit plan.
2.  **Audit plan**: More detailed, shows how the overall strategy will be implemented.

::: panel-tabset
## Audit Strategy

The key components of the audit strategy are:

1.  Understanding the client, and its environment.
2.  Materality threshold. What is considered material?
3.  Risk assessment. What are the risky areas for potential material misstatement?
4.  Nature, extent, and timing of audit procedures.
5.  Direction of the audit, who is supervising, and generally how review of the audit work will be undertaken.

## Audit Plan

The audit plan ensures the following:

1.  Attention (in-depth planning) is paid to the most important areas (high risk areas).
2.  Potential problems/risks are identified early.
3.  The audit is properly organised and managed.
4.  Work is assigned to the appropriate member of the audit team, and team members receive direction and supervision of team members.
5.  Reviews by more senior auditors are planned and facilitated.
:::

<br />

### Understanding the Client

ISA (UK) 315 requires auditors to gain an understanding of the client. This is because [it is necessary to understand what areas have higher risk of fraud/error, in order to design an effective audit strategy and plan.]{.mark}

Specifically, auditors should understand:

-   The industry and regulatory environment of the client, which can help identify risks.
-   Nature of the client, including the client's selection and application of accounting policies.
-   Objectives and strategy of the client, and related business risks, which may affect the risk of material misstatement.
-   Measurement and review of the client's financial performance. This could indicate pressure on directors to commit fraud.
-   The strength and effectiveness of internal controls at preventing errors/fraud. If these are weak, the risk of material misstatement is higher.

Auditors also need to understand the client's financial reporting framework, and its accounting policies.

::: panel-tabset
## Financial Reporting Framework

-   What are the accounting principles and industry-specific accounting principles.
-   Reporting of revenue recognition.
-   Accounting for financial instruments.
-   Reporting of foreign currency assets, liabilities, and transactions.
-   Accounting principles for unusual or complex transactions.

## Accounting Policies

-   What are the methods used to recognise, measure, and disclose significant and unusual transactions? For example, foreign transactions.
-   How do they use accounting policies in controversial or emerging areas, where there is a lack of regulation, guidance, or consensus?
-   How do they deal with changes in the environment that may require a change in accounting policies.
-   What financial reporting standards, laws, and regulations that are new to the client.
:::

To get this information, auditors can ask the client's management, conduct analytical procedures, observe processes, and inspect documents and assets.

<br />

### Audit Risk

Auditors do not want to give a wrong opinion, since shareholders/users depend on the auditor's opinion. Thus, auditors want to lower the audit risk of an incorrect opinion, such as failing to detect fraud/errors.

The risk of an audit (audit risk) is calculated as follows:

> **Audit Risk** $=$ **Inherent Risk** $\times$ **Control Risk** $\times$ **Detection Risk**

::: panel-tabset
## Inherent Risk

-   The client's risk of error/fraud, which cannot be controlled by auditors. This is usually related to the business/industry/regulatory environment.
-   For example, if the management is under pressure, there is an inherent risk of fraud due to this pressure.
-   If certain items/transactions are new, complex, one-off, or subjective, they are high risk.

Pg. 48 see more

## Control Risk

-   How strong a client's internal controls are to detect the inherent risk of error/fraud.
-   Stronger controls mean less control risk. Weaker controls means higher control risk. This makes sense - weaker controls are more likely to fail to detect errors/fraud.
-   Auditors generally cannot control this as well.

See the [internal controls page](controls.qmd) for more details on how controls work, and how to evaluate controls.

## Detection Risk

The risk that auditors fail to detect material misstatements. If inherent risk and control risk are higher, auditors need to reduce detection risk to lower audit risk overall.

To lower detection risk, auditors can:

-   Increase the sample size that they are testing, especially for accounts with high inherent/control risk.
-   Lower the materiality threshold.
-   Improve the quality of evidence to make sure it is sufficient and appropriate.
:::

::: {.callout-note collapse="true" appearance="simple"}
## Sustainability Risk

Risks also exist in relation to climate change. These include:

-   **Physical Risks**: risks from the physical effects of climate change, like extreme weather and storms. For example, dependent on supply chains/stock affected by climate change, such as farming and storms.
-   **Transitional Risks**: Risks relating to shifts to a low-carbon economy, such as changes to policy, regulation, technology, and market.

These are important because they can affect the financial statements. For example, destroyed assets/inventory.
:::

::: {.callout-note collapse="true" appearance="simple"}
## Related Parties

-   A related party is a firm who is influenced, or has influence over the client. For example, company A's director is married to company B's (our client's) company.
-   There is nothing inherently wrong with transactions involving a related party. However, they do increase the potential of manipulation between the two parties.
-   Generally, there is the principle of **arm's length**: that if the two parties were not related, the transaction's prices would still make sense.
-   Related party transactions must be disclosed separately, even if arm's length is met. These are considered [material by nature]{.underline} (regardless of the size of the transaction).
-   Related parties can be difficult to identify, and if there is manipulation, these are often concealed from auditors.
:::

<br />

### Setting Materiality

Recall that a mistake is **material** if its [omission or misstatement could influence the economic decisions of users of the report.]{.mark}

When determining if a transaction/error is material, there are two ways to do this:

1.  Material based on the **size** of the transaction (common thresholds below). This is determined during the planning stage.
2.  Material based on the **nature**. For example, transactions between the company and its directors must be disclosed, as these are considered material *regardless* of size. Related party transactions are also material by nature.

In higher risk businesses, the tolerance level for mistakes is lower, so we set the materiality threshold to the lower end of these ranges.

| Item              | Threshold Size |
|-------------------|----------------|
| Profit before tax | 5% to 10%      |
| Revenue           | 0.5% to 1%     |
| Total Assets      | 1% to 2%       |

: {.bordered tbl-colwidths="\[50,50\]"}

::: {.callout-note collapse="true" appearance="simple"}
## Performance Materiality

Performance materiality is an amount set by the auditor *lower* than the materiality threshold of the financial statements to reduce the risk of a specific account.

-   For example, if one branch of a large company is accused of fraud, you might have a special performance materiality for that branch, while the other branches are at the normal threshold.
:::

::: {.callout-note collapse="true" appearance="simple"}
## Sustainability Materiality

In sustainability assurance, materiality is assessed in a similar way.

-   ISSB sustainability materiality: sustainability-related risks and opportunities that could reasonably affect the entity's prospects that could influence the decisions of users.
-   Double materiality is a concept which considers not only the sustainability issues that reate financial risks for a company, but also the materiality of a company's impact on people and the environment.
:::

<br />

### Analytical Procedures

Analytical procedures is comparing non-financial information (like expectations based on experience) to actual financial information. Inconsistencies in comparisons may indicate potential risk.

-   Ex. During the pandemic lockdowns, we might assume an airline would have a difficult year, and expect a net loss. If the airline actually has a net profit, that is an inconsistency that could be a result of errors/fraud.

Analytical procedures are mandatory at planning to identify potential risks, according to ISA (UK) 315. They are also required to be used to assist forming an overall conclusion based on ISA (UK) 520.

::: {.callout-note collapse="true" appearance="simple"}
## Limitations of Analytical Procedures

-   They generally require strong background knowledge and experience of the client, which may be limited if the client is new.
-   They generally require experienced staff to be effective.
-   The quality of the procedure depends on the reliability of the sources.
:::

Often, when comparing in analytical procedures, we will need to use **ratios** to see how their value or how they have changed, which can be used in the comparison with our expectations.

::: panel-tabset
## Performance

+-----------------------------------+---------------------------------------------------------+-----------------------------------------------------------------------+
| Ratio                             | Calculation                                             | Purpose                                                               |
+===================================+=========================================================+=======================================================================+
| Gross Profit Margin               | gross profit $\div$ revenue                             | Assesses profitability before taking operating expenses into account. |
+-----------------------------------+---------------------------------------------------------+-----------------------------------------------------------------------+
| Operating/Net Margin              | operating profit $\div$ revenue                         | Assess profitability with operating expenses included.                |
+-----------------------------------+---------------------------------------------------------+-----------------------------------------------------------------------+
| Cost of Sales Percent             | cost of sales $\div$ revenue                            | How much costs of inventory make up of revenue.                       |
+-----------------------------------+---------------------------------------------------------+-----------------------------------------------------------------------+
| Operating Cost Percent            | operating expenses $\div$ revenue                       | How much operating expenses make up of revenue.                       |
+-----------------------------------+---------------------------------------------------------+-----------------------------------------------------------------------+
| Return on Capital Employed (ROCE) | operating profit $\div$ (equity + net debt)             | Effective use of resources.                                           |
+-----------------------------------+---------------------------------------------------------+-----------------------------------------------------------------------+
| Return on Shareholder's Fund      | operating profit $\div$ (share capital + share reserve) | Effective use of resources.                                           |
+-----------------------------------+---------------------------------------------------------+-----------------------------------------------------------------------+

: {.bordered tbl-colwidths="\[20,35,45\]"}

## Liquidity/Solvency

+----------------+-----------------------------------------------------------------------+---------------------------------------------------------+
| Ratio          | Calculation                                                           | Purpose                                                 |
+================+=======================================================================+=========================================================+
| Current Ratio  | current assets $\div$ current liabilities                             | Ability to pay liabilities due soon with liquid assets. |
+----------------+-----------------------------------------------------------------------+---------------------------------------------------------+
| Quick Ratio    | (receivables + cash + current investments) $\div$ current liabilities | Ability to pay liabilities due soon with liquid assets. |
+----------------+-----------------------------------------------------------------------+---------------------------------------------------------+
| Gearing Ratio  |                                                                       |                                                         |
+----------------+-----------------------------------------------------------------------+---------------------------------------------------------+
| Interest Cover |                                                                       |                                                         |
+----------------+-----------------------------------------------------------------------+---------------------------------------------------------+

: {.bordered tbl-colwidths="\[20,35,45\]"}

## Efficiency

| Ratio                    | Calculation | Purpose |
|--------------------------|-------------|---------|
| Net Asset Turnover       |             |         |
| Trade Receivables Period |             |         |
| Trade Payables Period    |             |         |
| Inventory Holding Period |             |         |

: {.bordered tbl-colwidths="\[20,35,45\]"}
:::

<br />

<br />

------------------------------------------------------------------------

# **Audit Evidence**

### Standard of Evidence

ISA (UK) 500 requires auditors to obtain **sufficient** and **appropriate** evidence to draw an audit opinion.

-   Sufficient evidence is about quantity. If you have higher risk, you will need more quantity of evidence. If you have lower materiality threshold, the more quantity of evidence is needed. Reasonable assurance will need more quantity of evidence than limited assurance.
-   Appropriate evidence is about the quality of evidence. Is the evidence reliable and from third parties? Is the evidence relevant to the financial statement assertions?

The highest quality form of evidence is either auditor generated or from an independent third party. Original documents are better than copies. Written evidence is better than oral evidence.

Audit evidence is relevant depending on what we are considering:

::: panel-tabset
## Transactions/Events

For transactions/events, relevant evidence includes:

-   **Occurence**: proof that the transaction occurred. For example, actually having the product, or an invoice.
-   **Completeness**: all transactions that should have been recorded are recorded.
-   **Accuracy**: the amounts of each transaction are accurately recorded. Invoices are useful for this.
-   **Cut-off**: transactions are recorded in the correct accounting period.
-   **Classification**: transactions are recorded in the correct accounts.
-   **Presentation**: transactions and events are accurately aggregated, clearly described, and disclosures are relevant and understandable.

## Account Balances

For account balances, relevant evidence includes:

-   **Existence**: assets, liabilities, and equity balances do exist. Physical visits to check assets are common.
-   **Rights and Obligations**: the client actually owns the assets, and the liabilities are indeed the obligations of the client. For example, look at purchase records, contact bank for cash account/loans.
-   **Completness**: all assets, liabilities, and equity are recorded.
-   **Accuracy, Valuation, and Allocation**: assets, liabilities, and equity are at the appropriate amounts.
-   **Classification**: assets, liabilities, and equity have been recorded in the correct accounts.
-   **Presentation**: assets, liabilities, and equity are accurately aggregated, clearly described, and disclosures are relevant and understandable.
:::

<br />

### Evidence Stage

Walkthrough tests begin at the start of the evidence stage. The tests and procedures you will do in the audit will depend on what happens in the walkthrough test.

-   Walkthrough test will get you a feel of the company.
-   It will help you decide if you expect the controls to be effective, or expect the controls to be ineffective.

Then, your audit evidence stage will depend on which expectation you have.

::: panel-tabset
## Effective Controls

If you expect effective controls after the walkthrough, the steps you will take will be:

1.  Do strong tests of controls. Note if the tests match your expectation.
2.  *If controls are found to be effective*, you can do limited audit testing due to limitations of any control system.
3.  *If controls are found to be ineffective*, you should conduct full substantive testing.

## Ineffective Controls

If you do not expect controls to be effective, the steps you will take are:

1.  Skip tests of controls, since we assume they will be ineffective.
2.  Conduct full substantive testing.
:::

You can do this for each separate account/transaction. For example, if most controls are expected to be strong, but there are certain unusual/complex/one-off transactions, you can apply the ineffective controls assumption to those.

<br />

### Substantive Procedures

Substantive procedures are tests with numbers. ISA (UK) 500 sets out the following types of procedures:

-   **Inspection**: examining records, documents, or physcial assets. For example, an auditor could look at an invoice to confirm the cost of inventory. Third party documentation (like invoices, certificates) are more reliable than internally created documents. Inspection can provide evidence regarding the existence of things, the value of things, the rights and obligations (like in a contract), and the completeness of things. Inspection may not work well for intangible items like goodwill.
-   **Observation**: watching a process or procedure being performed. For example, observe a firm's staff counting inventory. Observation is useful for confirming a process is performed as described. However, be aware that processes may not be the same when observed vs. unobserved.
-   **Inquiry and Confirmation**: regards asking staff (inquiry) or third-parties (confirmation). This is useful for understanding processes or obtaining explanations. Confrimation from third parties (banks, customers) is a strong form of evidence. Be aware that oral responses are less reliable than written confirmation.
-   **Recalculation and Reperformance**: checking the mathematical accuracy of documents and records. This is strong evidence as the auditor does it directly. For example, the auditor recalculates the depreciation to confirm they match the accounts. Reperformance is similar to recalculation, but not with math. Basically, do the same thing that the firm did previously.
-   **Analytical Procedures**: like done in the planning stage. In the evidence stage, if inconsistency of expectations and figures are unacceptable, seek further evidence.
-   **Remote Auditing Techniques**: this is inspection, but remote. For example, observing inventory counts through a live video, sharing documents electronically, and interviews via video call. This is useful when physical access is limited.

Some accounts require estimation, such as depreciation, allowance for receivables, and provisions. Since these are subjective, they are at risk of management bias. To audit these estimates, the common accounting procedures are:

-   Review and test the process used by management to develop the estimate. Is it reasonable?
-   Use an independent expert to make an estimate for comparision with the company's figure.
-   Review subsequent events (events after the year-end) for confirmation of the accuracy.
-   Test the operating effectiveness of the controls over how management made the estimates.

<br />

### Automated Tools

Modern accounting systems use computer software, so using technology to carry out audit procedures is common. There are two ways to use automate tools:

+---------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Test Data                                                                                                     | Audit Software                                                                                                                               |
+===============================================================================================================+==============================================================================================================================================+
| Can be used as a test of control.                                                                             | Used for reperformance and recalculation in substantive procedures.                                                                          |
+---------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Auditor's data (real or fake) is put into the client's system. This tests the controls in the system.         | Using client data (real) into the auditor's system, to recalculate and reperform transactions. It can also be used to conduct data analysis. |
+---------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Examples:                                                                                                     | Examples:                                                                                                                                    |
|                                                                                                               |                                                                                                                                              |
| -   Enter data with a timesheet with hours outside the normal range to check if the system rejects it.        | -   Reperformance to check the values in accounts.                                                                                           |
| -   Enter a valid purchase invoice to check the system correct allocates the purchase to the correct account. | -   Transaction analysis: matching purchase orders, goods received notes, and invoices.                                                      |
|                                                                                                               | -   Analytical procedures: analysing revenue trends by product or region.                                                                    |
|                                                                                                               | -   Judgemental areas: using sensitivity analysis to test assumptions on the net realisable value of inventory.                              |
+---------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+

: {.bordered tbl-colwidths="\[50,50\]"}

<br />

### Directional Testing

A mistated balance can be overstated (too large) or understated (too low). Generally, the risk is one direction. For example, companies rarely want to understate revenue or overtate expenses.

Testing for overstated and understated balances is different. For example, if you are testing non-current assests, you have the following sources/accounts/records:

1.  Financial statements (non-current assets section).
2.  Non-current asset register (an excel sheet of all non-current assets).
3.  Physical assets (the actual non-current assets).

+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Test Overstatement                                                                                                                                                    | Test Understatement                                                                                                                                                                              |
+=======================================================================================================================================================================+==================================================================================================================================================================================================+
| 1.  Start with financial statements.                                                                                                                                  | 1.  Start with the physical assets you can see being used in the client's business.                                                                                                              |
| 2.  Check the non-current asset register. See if it agrees with the financial statement.                                                                              | 2.  See if these physical assets exist in the non-current asset register.                                                                                                                        |
| 3.  Select a sample of assets in the non-current asset register.                                                                                                      | 3.  If they are present, check they are also in the financial statements.                                                                                                                        |
| 4.  Perform physical checks of the sampled assets and confirm they all exist.                                                                                         |                                                                                                                                                                                                  |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Why? If assets are overstated, that means some on the financial statements don't exist in real life. So you start from the financial statements and check they exist. | Why? If assets are understated, some assets that are being used aren't on the financial statements. Thus, start from the physical assets, and check all of them are on the financial statements. |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {.bordered tbl-colwidths="\[50,50\]"}

<br />

### Audit Sampling

In audit, we almost never check every transaction. We use a subset sample of the transactions to determine if there are material misstatements.

-   There are some transactions, such as high-value transactions, which will always be tested. These are not sampled.

The sampling procedure is as follows:

1.  Identify the population. If we are auditing receivables, then receivables is our population.
2.  Identify sampling unit. If we are auditing receivables, then invoices of credit customer purchases are the unit.
3.  Select sample (see below).
4.  Identify errors within the sample, and draw conclusions.

The way we select samples can be of many different ways.

-   Random selection: we randomly sample from the population.
-   Systematic selection: we randomly select the first unit for the sample, then maintain the same interval between selections. Ex. invoice 5, 10, 15, etc.
-   Money sampling unit: every £1 in the population has an equal chance of being selected. So the unit is actually every £1, not each invoice.
-   Haphazard sampling: just taking a sample manually without statistical theory.

Having a larger sample means lower detection risk, thus lowering the audit risk and creating a higher level of assurance.

**Sampling risk** is the risk that your sample might not reflect the entire population, leading to incorrect conclusions. For example, if you under-sample transactions that are likely to be fraudulent, you are likely to miss errors/fraud.

<br />

### Errors and Mistatements

Once an auditor has tested a sample of items, they must draw conclusions both to the sample, but also the entire account population.

Things to consider include:

1.  The nature of the errors identified. Are they true misstatements?
2.  The cause of the errors identified. Do they all have a pattern - i.e. all of them have messed up VAT? Do they all occur on one day?
3.  The impact on other parts of the audit. Does it affect the account balances, or do the errors cancel out? How does it affect the accounting equation.
4.  The probable misstatement in the population. Determine how frequently based on the sample, the misstatement will be repeated in the unsampled population. If the total misstatement is material, then additional testing needs to be done.

The auditor must communicate all misstatements to management, and request they to be corrected, no matter if they are material or immaterial.

-   If a client refuses to correct a material error, first understand why management refuses. Double check it is a misstatement. If it is material, you will modify the opinion (implied opinion, see below).
-   If a misstatement is not material, and the management refuses to correct it, you do not need to modify the opinion (but it should be mentioned separately).

::: {.callout-note collapse="true" appearance="simple"}
## Misstatements Material in Nature

Some categories which are always material, no matter the size, include:

-   Affect compliance with laws and regulations.
-   Affect compliance with debt covenants.
-   Affect ratios used to evaluate financial position, results, or cash flows.
-   Increase the management's compensation (renumeration).
-   Related party transactions.
:::

<br />

<br />

------------------------------------------------------------------------

# **Conclusion and Reporting**

### Audit Opinions

The auditor's report contains two different options:

+---------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| Explicit Opinions                                                                                                   | Implied (Modified) Opinions                                                                    |
+=====================================================================================================================+================================================================================================+
| Always reported in a final opinion.                                                                                 | Only required if a material problem arises.                                                    |
+---------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| Presents the opinion on the financial statements:                                                                   | Reported under the following situations:                                                       |
|                                                                                                                     |                                                                                                |
| -   Are they true and fair?                                                                                         | -   Returns adequate for audit have not been received by branches not visited by the auditors. |
| -   Are they properly prepared in accordance to accounting standards?                                               | -   Accounts are not in agreement with the underlying accounting records.                      |
| -   Is the Information contained in the director's report and strategic is consistent with the financial statement? | -   Proper accounting records have not been kept.                                              |
|                                                                                                                     | -   Information and explanations required for the audit were not received.                     |
|                                                                                                                     | -   Directors remuneration disclosures required by law were not made.                          |
+---------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+

: {.bordered tbl-colwidths="\[50,50\]"}

<br />

### Audit Report Format

ISA (UK) 700 states the following must be included in the final audit report:

1.  Title, addressee, and date of report.
2.  Auditor's opinion on the financial statements, and basis for opinion.
3.  Key audit matters (listed companies), such as high risk, significant judgmental items, and significant transactional events.
4.  Management and auditor responsibilities.
5.  Explanation of the extent to which the audit was capable of detecting irregularities, including fraud.
6.  Going concern section, and opinion on other matters (see above).
7.  Additional explanations/definitions of an assessment of risks of material misstatement, application of materiality, and overview of the scope of the audit. This is to close the expectations gap.
8.  Name and signature of the engagement partner, and their address.

::: {.callout-note collapse="true" appearance="simple"}
## Other Assurance Reports

For non-audit assurance engagements, a few things need to be included:

1.  Identification and description of the subject matter (is it sustainability, due dilligence?)
2.  Identification of criteria.
3.  Any inherent limitations which exist.
4.  Any restrictions upon the purpose/user.
5.  Work performed in accordance to which set of standards.
6.  Conclusion must be negatively expressed (limited assurance).
:::